### ISSUE TITLE
peewee create index Error

### ISSUE THREAD

**Issue by rfyiamcool** [coleifer/peewee#1006]
I want to create table with index, But raise error.    Mysql peewee version = 2.8.1
```
class ArticleContent(Model):
    article_id = IntegerField()
    content = BlobField()
    content_md5 = CharField(null=True,default=''")

    class Meta:
        database = db
        db_table= 'mirro_article_content'
        indexes = (
           (('article_id','content_md5'), False)
        )
```

Error log:
```
Traceback (most recent call last):
  File "core/models.py", line 138, in <module>
    init_table_data()
  File "core/models.py", line 133, in init_table_data
    ArticleContent.create_table()
  File "/Library/Python/2.7/site-packages/peewee.py", line 4562, in create_table
    cls._create_indexes()
  File "/Library/Python/2.7/site-packages/peewee.py", line 4586, in _create_indexes
    db.create_index(cls, fields, unique)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3549, in create_index
    'or tuple: "%s"' % fields)
ValueError: Fields passed to "create_index" must be a list or tuple: "article_id"

```

**Comment by coleifer** [comment]
You need a trailing comma after (('article_id', 'content_md5'), False) -- otherwise, since it's the only item in the outer-most parentheses, Python treats it as a normal expression rather than a tuple.
