### ISSUE TITLE
New release, please.

### ISSUE THREAD

**Issue by kdart** [coleifer/peewee#1027]
Hello. First of all, thanks for the great ORM. I'm using it in my project.  My project defines some custom fields. Now if I use the current distribution from pypi I get an exception thrown and my project basically crashes. But I see the fix for it is already in master. If I install from master everything works fine. It would be really nice, though, if my users could just get it off of pypi like the other packages. It's been like this for quite some time, so I thought I'd ping you to please do a point release to simplify our installation. Thanks!

**Comment by coleifer** [comment]
Definitely, can you tell me what commit in particular you're referring to?

**Comment by kdart** [comment]
The error is this:

```
Traceback (most recent call last):
  File "/opt/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Volumes/USER/Users/keith_dart/src/costest/costest/db/models.py", line 88, in <module>
    class EquipmentModel(BaseModel):
  File "/opt/lib/python3.5/site-packages/peewee.py", line 4479, in __new__
    field.add_to_class(cls, name)
  File "/opt/lib/python3.5/site-packages/peewee.py", line 1081, in add_to_class
    self._constructor = model_class._meta.database.get_binary_type()
  File "/opt/lib/python3.5/site-packages/peewee.py", line 407, in __getattr__
    raise AttributeError('Cannot use uninitialized Proxy.')
AttributeError: Cannot use uninitialized Proxy.
```

Because I'm also using the proxy object.

This fix is in b2d52ba7

**Comment by coleifer** [comment]
2.8.2 is pushed to PyPI.

**Comment by coleifer** [comment]
a33e8ccbd5b1e49f0a781d38d40eb5e8f344eee5
