### ISSUE TITLE
AttributeError: 'DatabaseError' object has no attribute 'message'

### ISSUE THREAD

**Issue by thacoon** [coleifer/peewee#1083]
Hi,

I tried this [gist](https://gist.github.com/thedod/11048875) that is referenced to in the  [peewee/playhouse/sqlcipher_ext.py](https://github.com/coleifer/peewee/blob/master/playhouse/sqlcipher_ext.py) file, line 51. When running this I get an `AttributeError: 'DatabaseError' object has no attribute 'message'` error message.  Using `.message` is also advcied in the [docs](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html?highlight=sqlcipher#sqlcipher-ext).

Full traceback:
```
$ python test.py
Passphrase: 
Traceback (most recent call last):
  File "/home/arch/.environments/passwordmanager_dev/lib/python3.5/site-packages/peewee.py", line 3676, in execute_sql
    cursor.execute(sql, params or ())
pysqlcipher3.dbapi2.DatabaseError: file is encrypted or is not a database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 54, in <module>
    db.get_tables()
  File "/home/arch/.environments/passwordmanager_dev/lib/python3.5/site-packages/peewee.py", line 3893, in get_tables
    'type = ? ORDER BY name;', ('table',))
  File "/home/arch/.environments/passwordmanager_dev/lib/python3.5/site-packages/peewee.py", line 3683, in execute_sql
    self.commit()
  File "/home/arch/.environments/passwordmanager_dev/lib/python3.5/site-packages/peewee.py", line 3507, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/arch/.environments/passwordmanager_dev/lib/python3.5/site-packages/peewee.py", line 134, in reraise
    raise value.with_traceback(tb)
  File "/home/arch/.environments/passwordmanager_dev/lib/python3.5/site-packages/peewee.py", line 3676, in execute_sql
    cursor.execute(sql, params or ())
peewee.DatabaseError: file is encrypted or is not a database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 58, in <module>
    if e.message != 'file is encrypted or is not a database':
AttributeError: 'DatabaseError' object has no attribute 'message'
```

I am currently using _peewee==2.8.3_ and _pysqlcipher3==1.0.2_.

**Comment by coleifer** [comment]
This works in Python 2.x, Python 3.x I guess doesn't work the same way.
