### ISSUE TITLE
MySQLDatabase object has no attribute '_meta'

### ISSUE THREAD

**Issue by ambross** [coleifer/peewee#1149]
This is my simple code
```
from peewee import *

db = MySQLDatabase('peeweetest',host='localhost',port=3306,user='root',passwd='****')

class Hello(db):
	name = CharField()
	age = CharField()

	class Meta:
		database = db

db.connect()
db.create_table(Hello,safe=True)
```

When I run this I get 
```
Traceback (most recent call last):
  File "tm.py", line 13, in <module>
    db.create_table(Hello,safe=True)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3769, in create_table
    return self.execute_sql(*qc.create_table(model_class, safe))
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2084, in inner
    return self.parse_node(fn(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2103, in _create_table
    meta = model_class._meta
AttributeError: 'MySQLDatabase' object has no attribute '_meta'
```
peewee version 2.8.5

**Comment by coleifer** [comment]
Hello should subclass Model, not your database instance.
