### ISSUE TITLE
pip3 install peewee error m wrong cython version

### ISSUE THREAD

**Issue by stanta** [coleifer/peewee#1224]
Hi, when I install peewee from pip, have an issue: ValueError: invalid version number '0.20.1post0'
on vagrant/   Ubuntu Trusty 14.04.5 LTS, says: 
    **elif StrictVersion(cython_version) < StrictVersion(cython_min_version):**

look:
root@lists:~/.pip# sudo pip3 install peewee
Downloading/unpacking peewee
  Downloading peewee-2.9.1.tar.gz (514kB): 514kB downloaded
  Running setup.py (path:/tmp/pip_build_root/peewee/setup.py) egg_info for package peewee
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/peewee/setup.py", line 29, in <module>
        elif StrictVersion(cython_version) < StrictVersion(cython_min_version):
      File "/usr/lib/python3.4/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/usr/lib/python3.4/distutils/version.py", line 143, in parse
        raise ValueError("invalid version number '%s'" % vstring)
    ValueError: invalid version number '0.20.1post0'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/peewee/setup.py", line 29, in <module>

    **elif StrictVersion(cython_version) < StrictVersion(cython_min_version):**

  File "/usr/lib/python3.4/distutils/version.py", line 40, in __init__

    self.parse(vstring)

  File "/usr/lib/python3.4/distutils/version.py", line 143, in parse

    raise ValueError("invalid version number '%s'" % vstring)

ValueError: invalid version number '0.20.1post0'

----------------------------------------
Cleaning up...

**Comment by coleifer** [comment]
That does indeed look like an invalid version number. Plus it's too old at any rate.

**Comment by stanta** [comment]
yeah, I downloaded cython sources from repo and go through "python setup install" - all became OK
