### ISSUE TITLE
Update method dont work

### ISSUE THREAD

**Issue by pandbsoftware** [coleifer/peewee#1273]
```python
from peewee import *
from playhouse.sqlite_ext import SqliteExtDatabase
import datetime

db = SqliteExtDatabase('lis22.db')

class BaseModel(Model):
    class Meta:
        database = db

class Lista(BaseModel):
    cuenta = CharField(unique=True)
    tiempo = CharField()

try:
    db.connect()
    db.create_tables([Lista])
except:
    pass

lista = Lista.create(cuenta="test", tiempo="a")
a = Lista.update(cuenta="test_changed").where(Lista.cuenta == "test")
a.execute()
Lista.get(Lista.cuenta == "test").cuenta

#output:  u'test'
```

**Comment by ardeaf** [comment]
Try property indenting and surrounding your code in code blocks.

**Comment by coleifer** [comment]
Please take the extra minute to ensure your code is properly formatted. I've done it for you this time as a courtesy.

**Comment by coleifer** [comment]
There is something wrong in your code or in the state of your database, because I get an error (as expected):

```python
Traceback (most recent call last):
  File "x.py", line 25, in <module>
    obj = Lista.get(Lista.cuenta == "test")
  File "/home/charles/pypath/peewee.py", line 4926, in get
    return sq.get()
  File "/home/charles/pypath/peewee.py", line 3185, in get
    % self.sql())
__main__.ListaDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."cuenta", "t1"."tiempo" FROM "lista" AS t1 WHERE ("t1"."cuenta" = ?)
```
