### ISSUE TITLE
[playhouse.dataset] Cannot process column name contain upper case char

### ISSUE THREAD

**Issue by renweibo** [coleifer/peewee#1276]
Here is the test case.
```python
    def test_case_2(self):
        db = DataSet('sqlite:///:memory:')
        books = db["books"]
        books.insert(bookId="ISBN1234567")
```
It should work but report following error:

```python
Traceback (most recent call last):
... ...
  File "/Users/renweibo/PycharmProjects/DailyNovel/common/test_driver.py", line 17, in test_case_2
    books.insert(bookId="ISBN1234567")
  File "/Users/renweibo/.virtualenvs/flask1/lib/python3.6/site-packages/playhouse/dataset.py", line 219, in insert
    return self.model_class.insert(**data).execute()
  File "/Users/renweibo/.virtualenvs/flask1/lib/python3.6/site-packages/peewee.py", line 4893, in insert
    fdict.update([(cls._meta.fields[f], insert[f]) for f in insert])
  File "/Users/renweibo/.virtualenvs/flask1/lib/python3.6/site-packages/peewee.py", line 4893, in <listcomp>
    fdict.update([(cls._meta.fields[f], insert[f]) for f in insert])
KeyError: 'bookId'
```

**Comment by renweibo** [comment]
Version:
- Python: 3.6.1
- peewee: 2.10.1

**Comment by coleifer** [comment]
d68ae11501face8f4eb6adfde82d8eda79728dc7
