### ISSUE TITLE
pwiz fails with cross-schema foreign keys

### ISSUE THREAD

**Issue by albireox** [coleifer/peewee#1295]
Not sure if there is a solution for this, but I'm trying to run pwiz on a schema that as foreign keys referencing other schema in the same DB. pwiz fails with

```
Traceback (most recent call last):
  File "/Users/albireo/.pyenv/versions/3.6.1/bin/pwiz.py", line 201, in <module>
    print_models(introspector, tables, preserve_order=options.preserve_order)
  File "/Users/albireo/.pyenv/versions/3.6.1/bin/pwiz.py", line 47, in print_models
    database = introspector.introspect(table_names=tables)
  File "/Users/albireo/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/site-packages/playhouse/reflection.py", line 520, in introspect
    src = columns[foreign_key.table][foreign_key.column]
KeyError: 'platedb_plate_pk'
```

where `platedb_plate_pk` is one of the columns that are a foreign key to a column on a different schema.

**Comment by coleifer** [comment]
Sorry, no plans to support that.

**Comment by mcastrogg** [comment]
Is this supported now?
