### ISSUE TITLE
utf8 stored inside BlobField errors

### ISSUE THREAD

**Issue by maugch** [coleifer/peewee#1299]
I have a database TEXT field stored as utf8mb4 on mysql which is translated to 
`description = BlobField(db_column='description', null=True)`
I tried to use the model and store data interactively without any problem. When I use the model in my program, I get :
```
Traceback (most recent call last):
  File "getSqlliteData.py", line 91, in <module>
    main()
  File "getSqlliteData.py", line 73, in main
    getStuffFromJson(item,id_recipe)
  File "/home/me/wp/python/database.py", line 244, in getRecipeFromJson
    recipe.save()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4971, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3303, in execute
    return self.database.rows_affected(self._execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2820, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3677, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3501, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3670, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
peewee.OperationalError: (1366, "Incorrect string value: '\\xA0  \\x0A  ...' for column 'description' at row 1")
```
The error comes when I try to update a row on the DB. Note that it does happen even if I do a get() and then a save(), which means I get my utf8 string from the database and then try to put it back on it with 0 changes (I should avoid that, but I'm still learning).

I think there is a problem on how data are stored on my Model, possibly a bug in peewee?
In order to avoid it, before i save() my object, I added the following two lines:

```python
if myitem.description is not None:
        myitem.description = u' '.join(myitem.description).encode('utf-8').strip()
```
I'm not sure how to write a simple test case. Is this description enough?

**Comment by coleifer** [comment]
I'm not quite following...if you're just looking to store text (encoded as UTF-8), the proper field to use is the `TextField`.

Can you try modifying your code to use `TextField` instead of `BlobField` and see if that resolves the issue?

**Comment by maugch** [comment]
Yes TextField works indeed. I think pwiz generated it as BlobField. I thought it was right since it can be huge. I am not sure now if the behaviour when it's BlobField is correct though.

**Comment by coleifer** [comment]
Glad it's working.
