### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment when trying to select from tables after 0.9.2 to 2.0.4 upgrade

### ISSUE THREAD

**Issue by skruger** [coleifer/peewee#130]
I'm upgrading my application to the current version of peewee and many of my models are failing the same way when I try to query them.  Most of my accesses happen within @classmethod calls so I did one manually from the command line and I get the same error.  I'm not sure what I'm doing wrong or what other details might help with this, but I thought I'd see if this was a known problem and I'm just messing up something simple.  Nothing has changed about the definition of this table in my upgrade process.  However, I did define a new model, called create_table(), and it seems to work.

Here is the stack trace.  I'm running python2.7 and installed peewee 2.0.4 using pip.

``` python
>>> XmppDomain.select().where(XmppDomain.fqdn == "kxgx.chatwith.it").get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 1285, in get
    return clone.execute().next()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 979, in next
    instance = self.iterate()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 965, in iterate
    return self.simple_iter(row)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 899, in simple_iter
    setattr(instance, f.name, f.python_value(row[i]))
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 218, in __set__
    instance._data[self.att_name] = value
TypeError: 'NoneType' object does not support item assignment
```

**Comment by savraj** [comment]
just ran in to a similar issue, fixed by calling super at the top of my model's __init__ as referenced in #118
