### ISSUE TITLE
No such module: FTS4

### ISSUE THREAD

**Issue by Billmike** [coleifer/peewee#1306]
Traceback (most recent call last):
  File "app.py", line 88, in <module>
    main()
  File "app.py", line 84, in main
    database.create_tables([Entry, FTSEntry], safe=True)
  File "C:\Users\Billmike\Documents\charlesblog\blog\lib\site-packages\peewee.py", line 3855, in create_tables
    create_model_tables(models, fail_silently=safe)
  File "C:\Users\Billmike\Documents\charlesblog\blog\lib\site-packages\peewee.py", line 5294, in create_model_tables
    m.create_table(**create_table_kwargs)
  File "C:\Users\Billmike\Documents\charlesblog\blog\lib\site-packages\playhouse\sqlite_ext.py", line 243, in create_table
    cls._meta.database.create_table(cls, options=options)
  File "C:\Users\Billmike\Documents\charlesblog\blog\lib\site-packages\playhouse\sqlite_ext.py", line 970, in create_table
    return self.execute_sql(sql, params)
  File "C:\Users\Billmike\Documents\charlesblog\blog\lib\site-packages\peewee.py", line 3775, in execute_sql
    self.commit()
  File "C:\Users\Billmike\Documents\charlesblog\blog\lib\site-packages\peewee.py", line 3598, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Users\Billmike\Documents\charlesblog\blog\lib\site-packages\peewee.py", line 3768, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such module: FTS4

**Comment by coleifer** [comment]
You don't have the SQLite FTS4 extension. You'll need to either compile it as a standalone and load it at run-time, or recompile SQLite with full-text search feature enabled. https://sqlite.org/fts3.html

**Comment by soufianesabiri** [comment]
Hello, I am using Anaconda with Python 3.7, how can I install FTS4 extension?

**Comment by coleifer** [comment]
I'd suggest asking anaconda.
