### ISSUE TITLE
peewee, flask and python3.6 

### ISSUE THREAD

**Issue by yauler** [coleifer/peewee#1343]
`sqlite3_lib_version = sqlite3.sqlite_version_info
AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'`
from playhouse/berkeleydb.py
how to fix it?

**Comment by coleifer** [comment]
You need the standard library sqlite3 installed at the very least.

**Comment by ciscoo** [comment]
Is there a way to avoid using sqlite3 all together?
Or is sqlite3 a peer dependency of peewee?

I'm encountering the same error on AWS Lambda. In my `models.py` I have the following defined:

```
from peewee import *
from playhouse.db_url import connect

db = connect(os.environ.get('DATABASE_URL'))

class BaseModel(Model):
    class Meta:
        database = db

# more models
# ...
```

And when the lambda is executed, I get the following:

```
START RequestId: ... Version: $LATEST
module initialization error: 'NoneType' object has no attribute 'sqlite_version_info'
```

**Comment by coleifer** [comment]
What version of Peewee are you using? Could you share the full traceback? It seems that this shouldn't occur in the latest 2.x code:

https://github.com/coleifer/peewee/blob/master/playhouse/sqlite_ext.py#L70-L73

**Comment by avish-3pg** [comment]
Still facing the sqlite3 issue, even though we are using peewee==2.10.1. Please advice at the earliest. Thank you.

Error Stack Trace -
'NoneType' object has no attribute 'sqlite_version_info': AttributeError
Traceback (most recent call last):
File "/var/task/handler.py", line 511, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 242, in lambda_handler
return handler.handler(event, context)
File "/var/task/handler.py", line 335, in handler
app_function = self.import_module_and_get_function(whole_function)
File "/var/task/handler.py", line 233, in import_module_and_get_function
app_module = importlib.import_module(module)
File "/var/lang/lib/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 978, in _gcd_import
File "", line 961, in _find_and_load
File "", line 950, in _find_and_load_unlocked
File "", line 655, in _load_unlocked
File "", line 678, in exec_module
File "", line 205, in _call_with_frames_removed
File "/var/task/schedular.py", line 16, in 
import models_postgres as models
File "/var/task/models_postgres.py", line 4, in 
from playhouse.db_url import connect
File "/var/task/playhouse/db_url.py", line 118, in 
from playhouse.berkeleydb import BerkeleyDatabase
File "/var/task/playhouse/berkeleydb.py", line 10, in 
sqlite3_lib_version = sqlite3.sqlite_version_info
AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'

**Comment by coleifer** [comment]
8ba62478f7ce4fc3890fad0d1c42e851a382bdd4
