### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'

### ISSUE THREAD

**Issue by avish-3pg** [coleifer/peewee#1360]
@coleifer Still facing the sqlite3 issue, even though we are using peewee==2.10.1. Please advice at the earliest. Thank you.

Error Stack Trace - 
'NoneType' object has no attribute 'sqlite_version_info': AttributeError
Traceback (most recent call last):
File "/var/task/handler.py", line 511, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 242, in lambda_handler
return handler.handler(event, context)
File "/var/task/handler.py", line 335, in handler
app_function = self.import_module_and_get_function(whole_function)
File "/var/task/handler.py", line 233, in import_module_and_get_function
app_module = importlib.import_module(module)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
File "/var/task/schedular.py", line 16, in <module>
import models_postgres as models
File "/var/task/models_postgres.py", line 4, in <module>
from playhouse.db_url import connect
File "/var/task/playhouse/db_url.py", line 118, in <module>
from playhouse.berkeleydb import BerkeleyDatabase
File "/var/task/playhouse/berkeleydb.py", line 10, in <module>
sqlite3_lib_version = sqlite3.sqlite_version_info
AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'

**Comment by coleifer** [comment]
Try 8ba62478f7ce4fc3890fad0d1c42e851a382bdd4 ?

**Comment by coleifer** [comment]
Closing due to inactivity.
