### ISSUE TITLE
execute_sql pass typle to MySQLdb if param is None

### ISSUE THREAD

**Issue by daoiqi** [coleifer/peewee#1394]
https://github.com/coleifer/peewee/blob/c6b5946a997e39f9939b0261e2b75c46acbac8f2/peewee.py#L3831

pass typle to MySQLdb if param is `None`, why not `None` to MySQLdb?

**Comment by coleifer** [comment]
?

**Comment by daoiqi** [comment]
MySQL

```python
sql = "select  DATE_FORMAT(MAX(NOW()),'%Y-%m-%d');   "
print database.execute_sql(sql)
```
```
Traceback (most recent call last):
  File "models.py", line 1332, in <module>
    print database.execute_sql(sql)
  File "/usr/lib/python2.6/site-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/lib/python2.6/site-packages/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 158, in execute
    query = query % db.literal(args)
TypeError: not enough arguments for format string

```

**Comment by coleifer** [comment]
Why aren't you parameterizing your query? You should use %s as the placeholder for those params, then pass them in as a tuple:

```
db.execute_sql('select date_format(max(now)), %s)', ('%Y-%m-%d'))
```
