### ISSUE TITLE
Can't create model instance without primary key

### ISSUE THREAD

**Issue by aachurin** [coleifer/peewee#1480]
```python
class Model1(TestModel):
            test1 = CharField(max_length=10)
            class Meta:
                primary_key = False

Model1.create(test1='1')  # fails.
```

```
Traceback (most recent call last):
  File "tests.py", line 412, in test_add_primary_key
    Model1.create(test1='1')
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 5049, in create
    inst.save(force_insert=True)
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 5165, in save
    self.insert(**field_dict).execute()
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 1447, in inner
    return method(self, database, *args, **kwargs)
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 1518, in execute
    return self._execute(database)
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 2150, in _execute
    return super(Insert, self)._execute(database)
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 1929, in _execute
    return self.handle_result(database, cursor)
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 2153, in handle_result
    return database.last_insert_id(cursor, self._query_type)
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 2931, in last_insert_id
    return cursor if query_type else cursor[0][0]
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 3345, in __getitem__
    self.fill_cache(item if item > 0 else 0)
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 3390, in fill_cache
    iterator.next()
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 3446, in next
    self.cursor_wrapper.iterate()
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 3365, in iterate
    self.initialize()  # Lazy initialization.
  File "/Users/peewee_test/lib/python3.6/site-packages/peewee-3.0.11-py3.6.egg/peewee.py", line 5842, in _initialize_columns
    node = node.unwrap()
AttributeError: 'bool' object has no attribute 'unwrap'
```

**Comment by coleifer** [comment]
Ewww, thank you.

**Comment by aachurin** [comment]
thx

**Comment by coleifer** [comment]
3.0.14 on PyPI.
