### ISSUE TITLE
flask_utils fails to import if libsqlite3 or sqlite-devel is not installed

### ISSUE THREAD

**Issue by bmamouri** [coleifer/peewee#1601]
Similar issue in the past: https://github.com/coleifer/peewee/issues/1218

I use PostgreSQL and my server does not have SQLite installed. When I want to import FlaskDB from flask_utils, I encounter the following issue:

```
  File "/home/ubuntu/presentation/api/server.py", line 4, in <module>
    from playhouse.flask_utils import FlaskDB
  File "/home/ubuntu/.local/share/virtualenvs/api-eYDWRPCf/lib/python3.6/site-packages/playhouse/flask_utils.py", line 12, in <module>
    from playhouse.db_url import connect as db_url_connect
  File "/home/ubuntu/.local/share/virtualenvs/api-eYDWRPCf/lib/python3.6/site-packages/playhouse/db_url.py", line 9, in <module>
    from playhouse.sqlite_ext import SqliteExtDatabase
  File "/home/ubuntu/.local/share/virtualenvs/api-eYDWRPCf/lib/python3.6/site-packages/playhouse/sqlite_ext.py", line 74, in <module>
    FTS_VER = sqlite3.sqlite_version_info[:3] >= (3, 7, 4) and 'FTS4' or 'FTS3'
```

The output of importing sqlite3:
```
ubuntu@REDACTED:~/wattcost/presentation/api$ python -m sqlite3
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/ubuntu/.pyenv/versions/3.6.5/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

It seems the root cause of the issue is [here](https://github.com/coleifer/peewee/blob/master/peewee.py#L30):

```
try:
    from pysqlite3 import dbapi2 as pysq3
except ImportError:
    try:
        from pysqlite2 import dbapi2 as pysq3
    except ImportError:
        pysq3 = None  # <= What is causing the problem
try:
    import sqlite3
except ImportError:
    sqlite3 = pysq3
else:
    if pysq3 and pysq3.sqlite_version_info >= sqlite3.sqlite_version_info:
        sqlite3 = pysq3
```

One way to solve this problem would be to convert FTS_VER into a lambda function so it can be evaluated lazily.

**Comment by bmamouri** [comment]
Oops, just realized the problem is already fixed in the [latest version](https://github.com/coleifer/peewee/blob/master/playhouse/sqlite_ext.py#L47).

Please close the issue. Thanks
