### ISSUE TITLE
When my program running in ubuntu 16.04, something error what is show.

### ISSUE THREAD

**Issue by 0xNone** [coleifer/peewee#1656]
This is error detail
```
web@VM-35-97-ubuntu:~/smallprogram/smallprogram-backend$ sudo python3.6 app.py 
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from view import routes
  File "/home/web/smallprogram/smallprogram-backend/view/__init__.py", line 180, in <module>
    from model.user import User
  File "/home/web/smallprogram/smallprogram-backend/model/user.py", line 17, in <module>
    class User(BaseModel):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 5044, in __new__
    cls._meta.set_primary_key(pk_name, pk)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4904, in set_primary_key
    self.add_field(name, field)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4846, in add_field
    field.bind(self.model, field_name, set_attribute)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3864, in bind
    self._constructor = model._meta.database.get_binary_type()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2959, in get_binary_type
    return sqlite3.Binary
AttributeError: 'NoneType' object has no attribute 'Binary'
```

And the database I use sqlite3, What's the proble?

**Comment by coleifer** [comment]
Does your basemodel class have a database assigned?

**Comment by coleifer** [comment]
How did you install python? Is it possible that you don't have the sqlite driver installed? You can test:

```pycon
>>> import sqlite3
>>> sqlite3
```

**Comment by coleifer** [comment]
Closing due to unresponsiveness.
