### ISSUE TITLE
model_to_dict don't work with ManyToManyField

### ISSUE THREAD

**Issue by Martin25699** [coleifer/peewee#1708]
Example code
```
import datetime
from peewee import *
from playhouse.shortcuts import model_to_dict
from playhouse.postgres_ext import PostgresqlExtDatabase

db = PostgresqlExtDatabase('test', user='test', password='tes', host='127.0.0.1', port=5432)


class BaseModel(Model):
    class Meta:
        database = db


class Tweet(BaseModel):
    content = TextField()
    timestamp = DateTimeField(default=datetime.datetime.now)


TweetUserProxy = DeferredThroughModel()


class User(BaseModel):
    username = TextField()
    tweets = ManyToManyField(Tweet, through_model=TweetUserProxy, backref='users')


class TweetUser(BaseModel):
    user = ForeignKeyField(User)
    tweet = ForeignKeyField(Tweet)


TweetUserProxy.set_model(TweetUser)

db.connect()
db.create_tables([User, Tweet, TweetUser])
user = User.create(username='Ivan')
tweet = Tweet.create(content='Hello World!')
TweetUser.create(user=user, tweet=tweet)
tweet2 = Tweet.create(content='Hello Not World!')
TweetUser.create(user=user, tweet=tweet2)

users = User.select()
for u in users:
    user_dict = model_to_dict(u, manytomany=True)
    print(user_dict)
```
Text error
```
Traceback (most recent call last):
  File "/Users/martin/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4129.34/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Users/martin/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4129.34/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/martin/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4129.34/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/###/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4129.34/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/###/PycharmProjects/###/models/test.py", line 44, in <module>
    user_dict = model_to_dict(u, manytomany=True)
  File "/Users/###/PycharmProjects/###/venv/lib/python3.6/site-packages/playhouse/shortcuts.py", line 63, in model_to_dict
    for rel_obj in getattr(model, name):
TypeError: getattr(): attribute name must be string
```

**Comment by coleifer** [comment]
Thanks for reporting, this is now fixed.

**Comment by Martin25699** [comment]
thx! so fast) when next release?

**Comment by coleifer** [comment]
There are quite a few changes, I'll probably tag 3.7.0 here in the next week or so.
