### ISSUE TITLE
NameError: name 'EnclosedClause' is not defined

### ISSUE THREAD

**Issue by jberkel** [coleifer/peewee#1744]
After upgrading to 3.x some FTS-related code stopped working:

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jan/projects/lexi/importer/src/test/python/test_search.py", line 8, in setUp
    self.reindex()
  File "/Users/jan/projects/lexi/importer/src/test/python/test_search.py", line 18, in reindex
    FTSHeadword.reindex()
  File "/Users/jan/projects/lexi/importer/src/main/python/lexi/models/fts.py", line 27, in reindex
    cls.optimize()
  File "/Users/jan/projects/lexi/importer/src/main/python/lexi/models/fts.py", line 55, in optimize
    return cls._fts_cmd('optimize')
  File "/Users/jan/projects/lexi/importer/build/virtual-env-python3/lib/python3.6/site-packages/playhouse/sqlite_ext.py", line 627, in _fts_cmd
    inner_clause = EnclosedClause(tbl)
NameError: name 'EnclosedClause' is not defined
```

Looks like `EnclosedClause` was removed in 3.x, but sqlite_ext still refers to it?

**Comment by coleifer** [comment]
Oversight on my part -- fixed. Thanks for reporting!
