### ISSUE TITLE
AttributeError: 'ValuesList' object has no attribute '_hash'

### ISSUE THREAD

**Issue by lephuongbg** [coleifer/peewee#1804]
I'm trying to filter valid ids from a list of ids like this:

```python
ids = [(1,), (2,), (3,)]
values = ValuesList(ids, ('id',), alias='ids')
list(Users.select(values.c.id)
      .join(values, p.JOIN.RIGHT_OUTER, cls.id == values.c.id)
      .where(cls.id.is_null()))
```

Produced SQL is OK but as soon as the query returns any results:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/var/task/.venv/src/peewee/peewee.py", line 3726, in __len__
    self.fill_cache()
  File "/var/task/.venv/src/peewee/peewee.py", line 3767, in fill_cache
    iterator.next()
  File "/var/task/.venv/src/peewee/peewee.py", line 3823, in next
    self.cursor_wrapper.iterate()
  File "/var/task/.venv/src/peewee/peewee.py", line 3739, in iterate
    self.initialize()  # Lazy initialization.
  File "/var/task/.venv/src/peewee/peewee.py", line 6555, in initialize
    self._initialize_columns()
  File "/var/task/.venv/src/peewee/peewee.py", line 6485, in _initialize_columns
    if isinstance(node, Column) and node.source == table:
```

**Comment by coleifer** [comment]
What's the actual error?
