### ISSUE TITLE
When create_tables: OperationalError: near "AS": syntax error

### ISSUE THREAD

**Issue by rafaleo** [coleifer/peewee#1832]
Hi. I've just installed peewee for the first time and try to execute some example. Based on your tutorial one (which works) I've created this simple code:
```
import peewee as pw

db = pw.SqliteDatabase('my_students.db')


class BaseModel(pw.Model):
    class Meta:
        database = db

class Student(BaseModel):
    name = pw.CharField(unique=True)
    points = pw.IdentityField()

db.connect()    
    db.create_tables([User, Student])
```
but it throws an error:
```
db.create_tables([User, Student])
Traceback (most recent call last):

  File "<ipython-input-83-9aeeec4d4064>", line 1, in <module>
    db.create_tables([User, Student])

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2789, in create_tables
    model.create_table(**options)

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 5670, in create_table
    cls._schema.create_all(safe, **options)

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 4919, in create_all
    self.create_table(safe, **table_options)

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 4805, in create_table
    self.database.execute(self._create_table(safe=safe, **options))

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2653, in execute
    return self.execute_sql(sql, params, commit=commit)

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2647, in execute_sql
    self.commit()

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2438, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 177, in reraise
    raise value.with_traceback(tb)

  File "C:\Anaconda3\lib\site-packages\peewee.py", line 2640, in execute_sql
    cursor.execute(sql, params or ())

OperationalError: near "AS": syntax error
```
Can't find any key difference between my code and tutorial. Please give me a hint if it's not a bug.

**Comment by coleifer** [comment]
What tutorial are you referring to? Please share the link.

The problem is your usage of `IdentityField`. You are using a `SqliteDatabase` in your example, but the documentation for `IdentityField` *clearly* states that this field is for postgresql 10.0 and newer ONLY.

http://docs.peewee-orm.com/en/latest/peewee/api.html#IdentityField

You should use an `IntegerField` for storing a point value.

**Comment by rafaleo** [comment]
Ok. I've found that `IdentityField` is somehow a wrong wolf, I've changed to `IntegerField` and it's all right. If it's not an issue just ignore this.
