### ISSUE TITLE
For Update in Subquery Fails with PostgreSQL

### ISSUE THREAD

**Issue by href** [coleifer/peewee#1858]
I'm trying to use SELECT .. FOR UPDATE SKIP LOCKED in a subquery to delete some records concurrently, and I think I stumbled upon a bug. Usually, my FOR UPDATE selects work fine in my Postgres Database, but this query cannot be rendered by Peewee.

When I run this example code:
```python
from peewee import Model
from peewee import AutoField
from peewee import TextField

class User(Model):
    id = AutoField()
    name = TextField()

User.delete().where(User.id.in_(User.select(User.id).for_update())).sql()
```

I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 1692, in sql
    return context.parse(self)
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 600, in parse
    return self.sql(node).query()
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 2374, in __sql__
    ctx.literal(' WHERE ').sql(self._where)
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 1295, in __sql__
    if op_in and Context().parse(self.rhs)[0] == '()':
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 600, in parse
    return self.sql(node).query()
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/Users/denis/.virtualenvs/centime/lib/python3.7/site-packages/peewee.py", line 2084, in __sql__
    raise ValueError('FOR UPDATE specified but not supported '
ValueError: FOR UPDATE specified but not supported by database.
```

This happens on PostgreSQL (not that I have specified that yet in this example), even though PostgreSQL supports FOR UPDATE. My other FOR UPDATE queries work out fine and when I remove the check leading up to the ValueError the query executes correctly as well.

**Comment by coleifer** [comment]
Well, the reason your specific example is bad is because you need to associate `User` model with a Postgres database instance. But the error is the same even after adding the database, just for different reasons. Fixed.

**Comment by href** [comment]
Thanks for fixing this so super quickly 🙂
