### ISSUE TITLE
TypeError: type str doesn't define __round__ method

### ISSUE THREAD

**Issue by faulander** [coleifer/peewee#1863]
Class Definition:
```
class Update(Model):
    date = TimestampField()
    model = TextField()
    provider = TextField()
    title = TextField()
    filename = TextField()
    collected = BooleanField()

    class Meta:
        database = db
```
Call:
```
    Update.get_or_create(
    date=up['date'], 
    model=up['model'], 
    provider=up['provider'], 
    title=up['title'], 
    defaults={'filename': up['filename'], 'collected': 0})
```

results in:
Traceback (most recent call last):
  File "/home/harald/.vscode/extensions/ms-python.python-2019.1.0/pythonFiles/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/home/harald/.vscode/extensions/ms-python.python-2019.1.0/pythonFiles/lib/python/ptvsd/__main__.py", line 348, in main
    run()
  File "/home/harald/.vscode/extensions/ms-python.python-2019.1.0/pythonFiles/lib/python/ptvsd/__main__.py", line 253, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/harald/Projects/bc/bc.py", line 34, in <module>
    defaults={'filename': up['filename'], 'collected': 0})
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 5677, in get_or_create
    return query.get(), False
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 6042, in get
    return clone.execute(database)[0]
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 1625, in inner
    return method(self, database, *args, **kwargs)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 1696, in execute
    return self._execute(database)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 1847, in _execute
    cursor = database.execute(self)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 2726, in execute
    sql, params = ctx.sql(query).query()
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 2067, in __sql__
    ctx.literal(' WHERE ').sql(self._where)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 1299, in __sql__
    .sql(self.lhs)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 1299, in __sql__
    .sql(self.lhs)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 1299, in __sql__
    .sql(self.lhs)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 1301, in __sql__
    .sql(self.rhs))
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 571, in sql
    return self.sql(Value(obj))
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 567, in sql
    return obj.__sql__(self)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 1225, in __sql__
    return ctx.value(self.value, self.converter)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 585, in value
    value = self.state.converter(value)
  File "/home/harald/Projects/bc/.venv/lib/python3.6/site-packages/peewee.py", line 4444, in db_value
    return int(round(value * self.resolution))
TypeError: type str doesn't define __round__ method

**Comment by coleifer** [comment]
The error occurs because you're passing a string as the value of a `TimestampField`. I'm not sure where your data is coming from or what form it is in, but you should probably convert it to either a python `datetime.datetime` object or an integer/float timestamp.
