### ISSUE TITLE
ForeignKeyField error

### ISSUE THREAD

**Issue by vannesspeng** [coleifer/peewee#1885]
class Message(BaseModel):
    sender = ForeignKeyField(User, verbose_name="发送者")
    receiver = ForeignKeyField(User, verbose_name="接受者")
    message_type = IntegerField(choices=MESSAGES_TYPES, verbose_name="类别")
    message = CharField(max_length=500, verbose_name="内容", null=True)
    parent_content = CharField(max_length=500, verbose_name="标题", null=True)

I do not kown why?  error like this:
Traceback (most recent call last):
  File "D:/python-study/gitcode/TornadoForum/Myforum/tools/init_db.py", line 8, in <module>
    from Myforum.apps.messages.models import Message
  File "D:\python-study\gitcode\TornadoForum\Myforum\apps\messages\models.py", line 18, in <module>
    class Message(BaseModel):
  File "C:\Users\sd\.virtualenvs\TornadoForum-e7zC9psu\lib\site-packages\peewee.py", line 4903, in __new__
    field.add_to_class(cls, name)
  File "C:\Users\sd\.virtualenvs\TornadoForum-e7zC9psu\lib\site-packages\peewee.py", line 1523, in add_to_class
    invalid('The related_name of %(field)s ("%(backref)s") '
  File "C:\Users\sd\.virtualenvs\TornadoForum-e7zC9psu\lib\site-packages\peewee.py", line 1517, in invalid
    raise AttributeError(msg % context)
AttributeError: The related_name of message.receiver ("message_set") is already in use by another foreign key.

**Comment by coleifer** [comment]
First: format your code. PLEASE. Here is a link: https://guides.github.com/features/mastering-markdown/

Second: you have two foreign-keys pointing to `User`. You need to specify a name for the back-reference that doesn't collide.

In your example, I would do something like:

```python
sender = ForeignKeyField(User, backref='outbox')
receiver = ForeignKeyField(User, backref='inbox')
```

Then you would do:

```python
user = User(...)
for message in user.outbox:  # Messages where "user" is "message.sender"
    # ...

for message in user.inbox:  # Messages where "user" is "message.receiver"
    # ...
```
