### ISSUE TITLE
Using a BlobField with a context manager results in a AttributeError on 3.9.4

### ISSUE THREAD

**Issue by poljar** [coleifer/peewee#1913]
The following code snippet results in an AttributeError on 3.9.4, 3.9.3 worked as expected:
```python
from peewee import SqliteDatabase, Model, BlobField

db = SqliteDatabase(":memory:")
class Table(Model):
    field = BlobField()

models = [Table]

with db.bind_ctx(models):
    db.create_tables(models)
```

The following error is thrown after running the code snippet:
```
Traceback (most recent call last):
  File "peewee_fail.py", line 14, in <module>
    db.create_tables(models)
  File "/usr/lib/python3.7/site-packages/peewee.py", line 5829, in __exit__
    model.bind(db, self.bind_refs, self.bind_backrefs)
  File "/usr/lib/python3.7/site-packages/peewee.py", line 6175, in bind
    cls._meta.set_database(database)
  File "/usr/lib/python3.7/site-packages/peewee.py", line 5667, in set_database
    hook(database)
  File "/usr/lib/python3.7/site-packages/peewee.py", line 4422, in _db_hook
    self._constructor = database.get_binary_type()
AttributeError: 'NoneType' object has no attribute 'get_binary_type'
```

The error doesn't happen if we're using a TextField  nor does it happen if we don't use a context manager for the database.

**Comment by coleifer** [comment]
Fixed. Pushing 3.9.5

**Comment by poljar** [comment]
Thanks for the quick response.
