### ISSUE TITLE
Peewee 3.9.5 throws TypeError on Windows running Python 3.7

### ISSUE THREAD

**Issue by sn0opy** [coleifer/peewee#1939]
I'm getting the following stack trace running on Windows with Python 3.7. The exact same code runs fine on Linux with Python 3.5 up to 3.7.

Is there anything, that has to be tweaked in my own code to run on Windows properly or is there an actual issue in Peewee's code? The Flask version being used on Linux and Windows is 1.0.3.

```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Python37\lib\site-packages\flask\app.py", line 1830, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Python37\lib\site-packages\flask\app.py", line 2106, in preprocess_request
    rv = func()
  File "C:\Python37\lib\site-packages\playhouse\flask_utils.py", line 181, in connect_db
    self.database.connect()
  File "C:\Python37\lib\site-packages\playhouse\pool.py", line 108, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
  File "C:\Python37\lib\site-packages\peewee.py", line 2882, in connect
    self._state.set_connection(self._connect())
  File "C:\Python37\lib\site-packages\playhouse\pool.py", line 125, in _connect
    ts, conn = heapq.heappop(self._connections)
TypeError: '<' not supported between instances of 'Connection' and 'Connection'
```

**Comment by coleifer** [comment]
What-the-what? Can you share how you're setting up and tearing down your connections? This seems like it should only happen if two conns are created at the *exact same timestamp*.

**Comment by sn0opy** [comment]
The code is open source. I'm linking the diff to the python2 to 3 migration. Unfortunately, I', not really that much into peewee and flask, but I hope the following diff helps anyway

https://github.com/cecpk/OSM-Rocketmap/commit/79539952592f7fb78c061373dabb664f533354d0#diff-541e2b217ba4a7d7859dae2cb443b6b7

**Comment by coleifer** [comment]
Not sure, can you provide a script to replicate?

Closing as I don't anticipate this being likely, but will gladly reopen if you can do so.
