### ISSUE TITLE
OperationalError on iregexp

### ISSUE THREAD

**Issue by Kotofey228** [coleifer/peewee#2010]
Have a query that works fine:
```
groups = Group.select().where((Group.codename.regexp(q)) | 
(Group.study_program.regexp(q)))
```
But the 'iregexp' one is giving an sql operational error:
```
groups = Group.select().where((Group.codename.iregexp(q)) | 
(Group.study_program.iregexp(q)))
```
Traceback:
```
Traceback (most recent call last):
  File "/Users/kotofey/Documents/SPBUBot/vbio/handlers/longpoll.py", line 46, in run
    self.bot.process_message(update['object'])
  File "/Users/kotofey/Documents/SPBUBot/vbio/bot.py", line 100, in process_message
    handler['function'](msg)
  File "bot.py", line 43, in handle_message
    group_list(user, m, keyboard)
  File "bot.py", line 82, in group_list
    if len(group_list) == 0:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 1897, in __len__
    self._ensure_execution()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 1879, in _ensure_execution
    self.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 1796, in inner
    return method(self, database, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 1867, in execute
    return self._execute(database)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 2038, in _execute
    cursor = database.execute(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 2994, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 2988, in execute_sql
    self.commit()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 2759, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 2981, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: near "IREGEXP": syntax error
```

**Comment by coleifer** [comment]
Your database (sqlite) doesn't support IREGEXP. Just use a normal regexp with case-insensitive matches/captures.
