### ISSUE TITLE
ModuleNotFoundError: No module named 'peewee'

### ISSUE THREAD

**Issue by 52lemon** [coleifer/peewee#2047]
i install peewee with pip3, and i got the error below
`
(logpress-tornado) F:\Projects\logpress-tornado>python3 manager.py --cmd=syncdb
Traceback (most recent call last):
  File "manager.py", line 17, in <module>
    from core import jinja_environment, smtp_server
  File "F:\Projects\logpress-tornado\core.py", line 7, in <module>
    from lib.database import Database
  File "F:\Projects\logpress-tornado\lib\database.py", line 8, in <module>
    import peewee
ModuleNotFoundError: No module named 'peewee'
`

**Comment by coleifer** [comment]
You must have some problem in your imports. This is definitely not the appropriate place for questions like this. Try stackoverflow.
