### ISSUE TITLE
Support indexing into array using expression w/postgres

### ISSUE THREAD

**Issue by coleifer** [coleifer/peewee#2085]
Question on SO: https://stackoverflow.com/questions/59708993/how-do-i-access-the-last-index-of-an-arrayfield-in-a-peewee-query-with-postgres

Example:

```python

from peewee import *
from playhouse.postgres_ext import *

db = PostgresqlExtDatabase('peewee_test')

class Test(Model):
    value = ArrayField(IntegerField)
    class Meta:
        database = db
        table_name = 'test_1'

db.connect()
db.create_tables([Test])

Test.create(value=[1,2,3,4])
Test.create(value=[2,7,5])
Test.create(value=[5,6,7])
VAL = 6

query = Test.select().where(Test.value[fn.array_length(Test.value) - 1] > VAL)
for row in query:
    print(row.value)
```

Error:

```python

Traceback (most recent call last):
  File "ww.py", line 22, in <module>
    query = Test.select().where(Test.value[fn.array_length(Test.value) - 1] > VAL)
  File "/home/charles/pypath/playhouse/postgres_ext.py", line 201, in __getitem__
    return ObjectSlice.create(self, value)
  File "/home/charles/pypath/playhouse/postgres_ext.py", line 135, in create
    parts = map(int, value.split(':'))
AttributeError: 'Expression' object has no attribute 'split'
```

**Comment by coleifer** [comment]
Fixed.
