### ISSUE TITLE
AttributeError: 'str' object has no attribute 'unwrap'

### ISSUE THREAD

**Issue by Rizhiy** [coleifer/peewee#2090]
I'm trying to retrieve rows from the database and get this error.
My table looks as follows:
```python
class Post(Model):
    date = DateField()
    user = ForeignKeyField(User, backref='numbers')
	number1 = Decimal(6,2)
    number2 = Decimal(6,2)

    class Meta:
		database = SqliteDatabase('data.db')
        primary_key = CompositeKey('date', 'user')
```

What can be the problem?

**Comment by coleifer** [comment]
Oh, I see - you're using `Decimal` instead of `DecimalField`. That's likely the issue.

**Comment by Rizhiy** [comment]
That's mistake in the code here. In my file it is correct.

**Comment by coleifer** [comment]
Then paste the full traceback??

**Comment by Rizhiy** [comment]
```
Traceback (most recent call last):
  File "tmp.py", line 22, in <module>
    for stuff in Post.select('date', 'user', 'number1'):
  File "/home/rizhiy/anaconda3/envs/data/lib/python3.7/site-packages/peewee.py", line 4287, in next
    self.cursor_wrapper.iterate()
  File "/home/rizhiy/anaconda3/envs/data/lib/python3.7/site-packages/peewee.py", line 4203, in iterate
    self.initialize()  # Lazy initialization.
  File "/home/rizhiy/anaconda3/envs/data/lib/python3.7/site-packages/peewee.py", line 7251, in _initialize_columns
    node = raw_node.unwrap()
AttributeError: 'str' object has no attribute 'unwrap'
```

**Comment by coleifer** [comment]
You need to read the docs. It's nowhere indicated that you pass string field-names into the select() method. You use the field instances themselves.

```python
Post.select(Post.date, Post.number1, ...)
```

Also selecting Post.user will just grab the user_id.
