### ISSUE TITLE
generate_models on SQLite database throws KeyError when database contains invalid foreign keys

### ISSUE THREAD

**Issue by kohavytank** [coleifer/peewee#2114]
Because foreign key constraints in SQLite can be disabled (and is disabled by default), it is possible to create a table with an invalid foreign key, like this:
```python
from peewee import SqliteDatabase
sqlite_db = SqliteDatabase(':memory:')
sqlite_db.execute_sql("""CREATE TABLE IF NOT EXISTS "table1" ("_id" INTEGER PRIMARY KEY,"name" TEXT,"value" INTEGER REFERENCES "non-existent-table"("non-existent-column"))""")
```

When running generate_models on such databases a KeyError is thrown.
```
>>> from playhouse.reflection import generate_models
>>> generate_models(sqlite_db)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kohavy\.virtualenvs\dtu--X-W94Eo\lib\site-packages\playhouse\reflection.py", line 775, in generate_models
    return introspector.generate_models(**options)
  File "C:\Users\kohavy\.virtualenvs\dtu--X-W94Eo\lib\site-packages\playhouse\reflection.py", line 674, in generate_models
    include_views)
  File "C:\Users\kohavy\.virtualenvs\dtu--X-W94Eo\lib\site-packages\playhouse\reflection.py", line 661, in introspect
    related_name=related_names.get(src))
  File "C:\Users\kohavy\.virtualenvs\dtu--X-W94Eo\lib\site-packages\playhouse\reflection.py", line 130, in set_foreign_key
    self.rel_model = model_names[foreign_key.dest_table]
KeyError: 'non-existent-table'
```

Is there a way to generate models for a database without the foreign key constraints? or a way to hook a callback to generate the appropriate field (IntegerField in the above case) when a foreign key is missing?

**Comment by coleifer** [comment]
Ehhh, man that's a really quite badly-broken schema. Not using constraints is one thing, but using constraints and then having them be extremely broken is not really something I intend to support.

If you need a workaround, just use pwiz' "-t" option to explicitly specify the list of un-broken tables, and then enter in the others by hand.
