### ISSUE TITLE
Error with bulk_update and UUID primary keys

### ISSUE THREAD

**Issue by spl0k** [coleifer/peewee#2155]
Hello,

It seems peewee doesn't serialize primary keys properly in `bulk_update()` when they're `UUIDField`s.

This code
```python
import logging
import uuid

from peewee import Model, UUIDField, IntegerField, SqliteDatabase

database = SqliteDatabase(":memory:")


class TestModel(Model):
    pk = UUIDField(primary_key=True, default=uuid.uuid4)
    i = IntegerField()

    class Meta:
        database = database


database.create_tables((TestModel,))

m1, m2 = [TestModel.create(i=i) for i in (1, 2)]
m1.i = 11
m2.i = 22

logger = logging.getLogger("peewee")
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)

TestModel.bulk_update((m1, m2), (TestModel.i,))
```

produces the following
```
('UPDATE "testmodel" SET "i" = CASE "testmodel"."pk" WHEN ? THEN ? WHEN ? THEN ? END WHERE ("testmodel"."pk" IN (?, ?))', [UUID('cec16f95-6bbe-4cb7-a4b7-89373dc7c895'), 11, UUID('046b94f6-154b-4f68-b9e8-4e447fd568a1'), 22, 'cec16f956bbe4cb7a4b789373dc7c895', '046b94f6154b4f68b9e84e447fd568a1'])
Traceback (most recent call last):
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 3090, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bulk.py", line 27, in <module>
    TestModel.bulk_update((m1, m2), (TestModel.i,))
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 6345, in bulk_update
    .where(cls._meta.primary_key.in_(id_list))
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 1877, in inner
    return method(self, database, *args, **kwargs)
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 1948, in execute
    return self._execute(database)
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 2433, in _execute
    cursor = database.execute(self)
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 3103, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 3097, in execute_sql
    self.commit()
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 2864, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "E:\projects\battledawn-server\env\lib\site-packages\peewee.py", line 3090, in execute_sql
    cursor.execute(sql, params or ())
peewee.InterfaceError: Error binding parameter 0 - probably unsupported type.
```

Using peewee version 3.13.2

**Comment by coleifer** [comment]
Fixed in 3.13.3
