### ISSUE TITLE
psycopg2.ProgrammingError: invalid dsn: invalid connection option "autoconnect"

### ISSUE THREAD

**Issue by kmakwana** [coleifer/peewee#2175]
OS : Ubuntu 20.04
Python version : 3.8.2
Psycopg2 version : 2.8.5
Peewee version : 3.7.0

I am trying to do database connection but it gives me following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 2600, in connect
    self._state.set_connection(self._connect())
  File "/usr/lib/python3/dist-packages/playhouse/pool.py", line 155, in _connect
    conn = super(PooledDatabase, self)._connect()
  File "/usr/lib/python3/dist-packages/playhouse/postgres_ext.py", line 431, in _connect
    conn = super(PostgresqlExtDatabase, self)._connect()
  File "/usr/lib/python3/dist-packages/peewee.py", line 3227, in _connect
    conn = psycopg2.connect(database=self.database, **self.connect_params)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 126, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/extensions.py", line 176, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "autoconnect"
```
But if I remove `autoconnect=False` then there is no error.

**Comment by coleifer** [comment]
Autoconnect was not added in 3.7.0: https://github.com/coleifer/peewee/blob/3.7.0/peewee.py#L2531-L2532
