### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by feelingnothing** [coleifer/peewee#2249]
Error:
```
{'name': 'VIP1', 'description': 'TEST1', 'price': 1.0, 'currency': 'rub', 'role_id': '735095020402769941'}
Traceback (most recent call last):
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\menus\__init__.py", line 638, in update
    await button(self, payload)
  File "c:\Users\dolabaeb\Desktop\paid projects\platezka-sample\menus\products.py", line 259, in select
    await self.pages[self.current_page - 1]['func']()
  File "c:\Users\dolabaeb\Desktop\paid projects\platezka-sample\menus\products.py", line 238, in role
    await self._complete_check()
  File "c:\Users\dolabaeb\Desktop\paid projects\platezka-sample\menus\products.py", line 162, in _complete_check
    Product(
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 6497, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 1886, in inner
    return method(self, database, *args, **kwargs)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 1957, in execute
    return self._execute(database)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 2442, in _execute
    cursor = database.execute(self)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 3112, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 3099, in execute_sql
    cursor.execute(sql, params or ())
OverflowError: Python int too large to convert to SQLite INTEGER
```

I tried to insert into `IntegerField` value `735095020402769941`, but got Python int too large to convert to SQLite INTEGER
After stackoverflow session I did create a ReallyBigIntegerField
```python
class ReallyBigIntegerField(Field):
    field_type = 'text'

    def db_value(self, value):
        return str(value)

    def python_value(self, value):
        return int(value)
``` 
but got the same error

After that I set up CharField instead of my custom one and got SAME error

*Every time I made changes, I deleted the database for migration

Forgot about my model
```python
class Product(BaseModel):
    id = CharField(default=uuid4)
    type = CharField(default=ROLE, choices=[ROLE])
    created_at = DateTimeField(default=datetime.now)
    name = CharField(max_length=256)
    description = CharField(max_length=2048)
    price = FloatField()
    currency = CharField(default=USD, choices=CURRENCY_TYPES)
    role_id = CharField(max_length=18)
```

**Comment by feelingnothing** [comment]
Forgot about my model
```python
class Product(BaseModel):
    id = CharField(default=uuid4)
    type = CharField(default=ROLE, choices=[ROLE])
    created_at = DateTimeField(default=datetime.now)
    name = CharField(max_length=256)
    description = CharField(max_length=2048)
    price = FloatField()
    currency = CharField(default=USD, choices=CURRENCY_TYPES)
    role_id = CharField(max_length=18)
```

**Comment by johanjk** [comment]
Have a look at the [docs](http://docs.peewee-orm.com/en/latest/peewee/models.html#field-types-table) there is a `BigIntegerField`, it should be sufficient for your use:
```
>>> v = 735095020402769941
>>> (v/(2**31-1) > 1)
True
>>> (v/(2**63-1) > 1)
False
```

**Comment by coleifer** [comment]
This works fine for me, I'm not sure what you've omitted but probably something important:

```python
from peewee import *                                                                                                 

db = SqliteDatabase(':memory:')

class BigIntField(TextField):
    def python_value(self, value):
        return int(value)

class Reg(Model):
    key = TextField()
    value = BigIntField()
    class Meta:
        database = db

db.create_tables([Reg])

r1 = Reg.create(key='k1', value=10)
r2 = Reg.create(key='k2', value=735095020402769941)

query = Reg.select()
for row in query:
    print(row.key, row.value, type(row.value))
```

Output:

```
k1 10 <class 'int'>                                                                                                  
k2 735095020402769941 <class 'int'>
```
