### ISSUE TITLE
TypeError: <lambda>() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by feelingnothing** [coleifer/peewee#2250]
My model:
```python
class Notification(BaseModel):
    id = CharField(default=uuid4, max_length=36)
    created_at = DateTimeField(default=datetime.now)
    channel = BigIntField()
    time = TimeField()
    title = CharField(max_length=256, null=True)
    description = CharField(max_length=2048, null=True)
    color = CharField(max_length=6, default='2f3136')
    image = CharField(null=True)
```
How im trying to save data:
```python
for h, m in self.data['intervals']:
    data = {k: v for k, v in deepcopy(self.data).items() if v is not None and k != 'intervals'}
    # data = {'channel': 742158931408846859, 'title': 'title'}
    # time is datetime.time
    # time = time(hour=2, minute=31)
    Notification.create(**data, time=time(hour=h, minute=m)).save()
```
Error I got
```python
Traceback (most recent call last):
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\menus\__init__.py", line 638, in update
    await button(self, payload)
  File "c:\Users\dolabaeb\Desktop\paid projects\notifications\menus\notification.py", line 145, in end
    Notification.create(**data, time=time(hour=h, minute=m)).save()
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 6292, in create
    inst.save(force_insert=True)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 6499, in save
    pk = self.insert(**field_dict).execute()
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 1886, in inner
    return method(self, database, *args, **kwargs)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 1957, in execute
    return self._execute(database)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 2707, in _execute
    return super(Insert, self)._execute(database)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 2442, in _execute
    cursor = database.execute(self)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 3111, in execute
    sql, params = ctx.sql(query).query()
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 606, in sql
    return obj.__sql__(self)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 2684, in __sql__
    self._simple_insert(ctx)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 2544, in _simple_insert
    return self._generate_insert((self._insert,), ctx)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 2656, in _generate_insert
    return ctx.sql(CommaNodeList(all_values))
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 606, in sql
    return obj.__sql__(self)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 1752, in __sql__
    ctx.sql(self.nodes[n_nodes - 1])
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 606, in sql
    return obj.__sql__(self)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 1750, in __sql__
    ctx.sql(self.nodes[i])
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 606, in sql
    return obj.__sql__(self)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 1364, in __sql__
    return ctx.value(self.value, self.converter)
  File "C:\Users\dolabaeb\AppData\Local\Programs\Python\Python38\lib\site-packages\peewee.py", line 618, in value
    value = converter(value)
TypeError: <lambda>() takes 1 positional argument but 2 were given
```

And my `BigIntField` and `BaseModel`
```python
class BigIntField(TextField):
    python_value = lambda v: int(v)
    db_value = lambda v: str(v)

class BaseModel(Model):
    class Meta:
        database = db
```
(Just to clear some questions)

- [x] I tried to google it
- [x] I tried to sort out None's 

Also, I tried to find an example of using 'TimeField`, but didn't find it

version: peewee==3.13.3

**Comment by coleifer** [comment]
I shared a working example of this code, did you not see it? You are replacing methods with lambdas but they need to take the implicit "self" when called on the instance.

```python
# e.g.
python_value = lambda self, v: int(v)
```

Please do not post this kind of question on the issue tracker. It belongs on stackoverflow or you can ask on IRC. This is for peewee issues.
