### ISSUE TITLE
Encoding issue on some weird fields

### ISSUE THREAD

**Issue by joveice** [coleifer/peewee#2359]
Hey, I have some issues trying to read some weird fields. I get this encoding exception:
```
Traceback (most recent call last):
  File "D:/Projects/autocat-companion/app.py", line 275, in <module>
    main()
  File "D:/Projects/autocat-companion/app.py", line 173, in main
    for x in s:
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 6851, in __iter__
python-BaseException
    self.execute()
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 1898, in inner
    return method(self, database, *args, **kwargs)
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 1969, in execute
    return self._execute(database)
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 2141, in _execute
    cursor = database.execute(self)
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 3142, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 3136, in execute_sql
    self.commit()
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 2902, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "D:\Projects\autocat-companion\venv\lib\site-packages\peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: Could not decode to UTF-8 column 'RockerSettings' with text '╔T'
```

Now I got the same on sqlite3 and solved it by using [text factory](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.text_factory) as bytes
I tried to insert it on line 3403 in peewee.py and that seems to sort it out.

Is there any ways to do something like this without editing the library?
I'm trying to use it with this (which works great with the text_factory insert)
```
class LuabinField(BlobField):

    def db_value(self, value):
        return luabins.encode_luabins(value)

    def python_value(self, value):
        if value is not None:
            return luabins.decode_luabins(io.BytesIO(value))
```

**Comment by joveice** [comment]
```
db = SqliteDatabase(config.get('save_path'))
conn = db.connection()
conn.text_factory = bytes
```
This works, would this be a valid way?
Sorry for the dumb questions, but this is really new to me.

**Comment by coleifer** [comment]
Sqlite uses UTF8 (or UTF16) for text. It sounds like you have a weird encoding. I don't know the provenance of this database, but if you're using peewee's `TextField` then this is expressly for storing UTF8-encoded unicode text. If you need to store arbitrary binary data you should use the `BlobField`.
