### ISSUE TITLE
bulk_create does not work with bulk created foreignkey

### ISSUE THREAD

**Issue by elya5** [coleifer/peewee#2393]
Hi,

I have the following models:
```
class WWW(Model):
    mdate = CharField(null=True)
    key = CharField(null=True)
    title = CharField(null=True)
    url = CharField(null=True)

    class Meta:
        database = d

class AuthorField(Model):
    name = CharField()
    www = ForeignKeyField(WWW, backref='names')

    class Meta:
        database = d
```

I have to insert a lot of entries so I wanted to use bulk insertion. However I'm running into the following error (the first part is just to demonstrate that it works without `bulk_create`)
```
>>> a=WWW(title='test')
>>> b=AuthorField(name='testname')
>>> b.www = a
>>> a.save()
1
>>> b.save()
1
>>> a=WWW(title='test2')
>>> b=AuthorField(name='testname2')
>>> b.www = a
>>> WWW.bulk_create([a])
>>> AuthorField.bulk_create([b])
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: authorfield.www_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 6378, in bulk_create
    res = cls.insert_many(accum, fields=fields).execute()
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 1907, in inner
    return method(self, database, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 1978, in execute
    return self._execute(database)
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 2745, in _execute
    return super(Insert, self)._execute(database)
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 2474, in _execute
    cursor = database.execute(self)
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: authorfield.www_id
>>> 
```

It works if I save each of the `WWW`s individually but that is way slower. Is there any way around this?

**Comment by coleifer** [comment]
The bulk create API doesn't set the fk value automatically.

Just wrap it in a transaction and it will be plenty fast.
