### ISSUE TITLE
Incompleted transactions with PostgreSQL

### ISSUE THREAD

**Issue by rudyryk** [coleifer/peewee#240]
How to deal with incompleted transactions in PostgreSQL? It seems we can't make queries after single transaction fail. Instead we get: **psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block**

Here's minimal code sample to reproduce the issue:

``` Python
import peewee
db = peewee.PostgresqlDatabase(
            database='test',
            host='localhost',
            port=None,
            user='test',
            password=None)

class User(peewee.Model):
   username = peewee.CharField(max_length=50, unique=True)

   class Meta:
       database = db

User.create_table()
User.create(username='test')
```

So, I get single user with username "test". If I try to create another one, I'll get an error:

``` Python
>>> User.create(username='test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 2193, in create
    inst.save(force_insert=True)
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 2278, in save
    new_pk = insert.execute()
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 1623, in execute
    return self.database.last_insert_id(self._execute(), self.model_class)
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 1314, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 1721, in execute_sql
    res = cursor.execute(sql, params or ())
psycopg2.IntegrityError: duplicate key value violates unique constraint "user_username"
DETAIL:  Key (username)=(test) already exists.
```

And that's predictable and fine! (By the way, how should we catch this kind of exception?)

But when I try to make another request, it fails:

``` Python
>>> User.get(username='test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 2203, in get
    return sq.get()
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 1521, in get
    return clone.execute().next()
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 1556, in execute
    self._qr = ResultWrapper(self.model_class, self._execute(), query_meta)
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 1314, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Users/test/.virtualenvs/test/lib/python3.3/site-packages/peewee.py", line 1721, in execute_sql
    res = cursor.execute(sql, params or ())
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block
```

And I need to drop database connection and create a new one to make it work again.

**Comment by romanek-adam** [comment]
I was hit by this issue too. The default value for `autorollback` parameter is wrong, but I guess it's set this way to maintain backward compatibility?

Nevertheless I assumed a rollback would be issued in case of any exception, but apparently I was wrong...

**Comment by coleifer** [comment]
What do you mean it's wrong? It's documented as being `False`.

**Comment by romanek-adam** [comment]
Yes, it is. But as pointed out in previous comments most people rely on deafults and this is not the expected behavior in most cases.

**Comment by rudyryk** [comment]
@romanek-adam But it is documented and backward compatible! It's generally not a good idea to change defaults one day.

Probably it would be good to add some notes on `autorollback` to [Transactions section in docs](
http://peewee.readthedocs.io/en/latest/peewee/transactions.html)
