### ISSUE TITLE
Peewee 2 does not work with python 3.10

### ISSUE THREAD

**Issue by ribx** [coleifer/peewee#2498]
The problem is, that the exports of the `collections` modules were moved to `collections.abc`:

```
docker run --rm -ti python:3.10 sh -c 'pip install cython &>/dev/null && pip install peewee==2.10.2'
....
Collecting peewee==2.10.2
  Downloading peewee-2.10.2.tar.gz (516 kB)
     |████████████████████████████████| 516 kB 3.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i073ept4/peewee_0592019e5eb643a48b6ef02e66fcd5d8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i073ept4/peewee_0592019e5eb643a48b6ef02e66fcd5d8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-efaxgva5
         cwd: /tmp/pip-install-i073ept4/peewee_0592019e5eb643a48b6ef02e66fcd5d8/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i073ept4/peewee_0592019e5eb643a48b6ef02e66fcd5d8/setup.py", line 64, in <module>
        version=__import__('peewee').__version__,
      File "/tmp/pip-install-i073ept4/peewee_0592019e5eb643a48b6ef02e66fcd5d8/peewee.py", line 124, in <module>
        from collections import Callable
    ImportError: cannot import name 'Callable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
    ----------------------------------------
```

```
$ docker run --rm -ti python:3.9
>>> from collections import Callable
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```

The fix should be quite simple, by just replacing `collections` with `collections.abc`.

I am stuck to peewee 2 because I am using this extension:
https://github.com/cour4g3/peewee-mssql

I can also create a PR.

**Comment by coleifer** [comment]
That version is not receiving patches, unfortunately. Your best bet is to fork it and patch it. You won't lose sync with upstream if you stay on 2.x.

**Comment by Suleman-Elahi** [comment]
I created updated fork of peewee-mssql: https://github.com/Suleman-Elahi/peewee-mssql
