### ISSUE TITLE
pwiz doesn't find installed psycopg (peewee.ImproperlyConfigured: Postgres driver not installed!)

### ISSUE THREAD

**Issue by NAN-CForadas** [coleifer/peewee#2565]
System Software Overview:
  macOS Monterey
  System Version:	macOS 12.3.1 (21E258)
  Kernel Version:	Darwin 21.4.0

  Python 3.10.4

```% python -m pwiz -H $HOSTNAME -p 5432 -e postgresql -v $DATABASE
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "pee-wee-testing/venv/lib/python3.10/site-packages/pwiz.py", line 222, in <module>
    introspector = make_introspector(engine, database, **connect)
  File "pee-wee-testing/venv/lib/python3.10/site-packages/pwiz.py", line 52, in make_introspector
    return Introspector.from_database(db, schema=schema)
  File "pee-wee-testing/venv/lib/python3.10/site-packages/playhouse/reflection.py", line 501, in from_database
    metadata = PostgresqlMetadata(database)
  File "pee-wee-testing/venv/lib/python3.10/site-packages/playhouse/reflection.py", line 264, in __init__
    cursor = self.execute('select oid, typname, format_type(oid, NULL)'
  File "pee-wee-testing/venv/lib/python3.10/site-packages/playhouse/reflection.py", line 165, in execute
    return self.database.execute_sql(sql, params)
  File "pee-wee-testing/venv/lib/python3.10/site-packages/peewee.py", line 3175, in execute_sql
    cursor = self.cursor(commit)
  File "pee-wee-testing/venv/lib/python3.10/site-packages/peewee.py", line 3159, in cursor
    self.connect()
  File "pee-wee-testing/venv/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "pee-wee-testing/venv/lib/python3.10/site-packages/peewee.py", line 3812, in _connect
    raise ImproperlyConfigured('Postgres driver not installed!')
peewee.ImproperlyConfigured: Postgres driver not installed!
```
```
(venv) (base) pee-wee-testing % pip freeze
click==8.1.3
Flask==2.1.2
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.1
peewee==3.14.10
psycopg==3.0.14
Werkzeug==2.1.2
```

**Comment by NAN-CForadas** [comment]
Sorry, I installed psycopg not psycopg2.  Please excuse me!

**Comment by coleifer** [comment]
You probably want to use `psycopg2` or `psycopg2-binary` as those are better supported by Peewee and can coexist alongside your install of `psycopg==3`.
