### ISSUE TITLE
Getting Type object has no attribute _meta. on create_tables

### ISSUE THREAD

**Issue by Waayway** [coleifer/peewee#2569]
Th error i'm getting is,
`AttributeError: type object 'Chat' has no attribute '_meta'. Did you mean: 'Meta'?`
Where Chat is random between the tables i'm making. My code is
```
import peewee
from peewee import *
from .database import db

class baseModel(peewee.ModelBase):
    class Meta:
        database = db


class User(baseModel):
    id = peewee.CharField(unique=True)
    username = peewee.CharField()
    email = peewee.CharField(unique=True)
    password = peewee.CharField()
    server_ids = peewee.ManyToManyField(model=None)
    friend_ids = peewee.ManyToManyField(model=None)

class Server(baseModel):
    id = peewee.CharField(unique=True)
    title = peewee.CharField()
    icon = peewee.CharField()
    chat_ids = peewee.ManyToManyField(model=None)

class Chat(baseModel):
    id = peewee.CharField(unique=True)
    title = peewee.CharField()
    description = peewee.CharField()
    server_id = peewee.ForeignKeyField(model=None)
    user_ids = peewee.ManyToManyField(model=None)
    message_ids = peewee.ManyToManyField(model=None)

class Message(baseModel):
    id = peewee.CharField(unique=True)
    content = peewee.CharField()
    send_time = peewee.DateTimeField()
    sender_id = peewee.ForeignKeyField(model=None)
    chat_id = peewee.ForeignKeyField(model=None)

def create_tables():
    with db:
        db.create_tables([User,Server,Chat,Message])
```
And it always fails on the last line.
Version of Peewee i'm running is 3.14.10
And Python 3.10

**Comment by coleifer** [comment]
You're extending peewee.ModelBase for some reason: `class baseModel(peewee.ModelBase):`

Change that to `class baseModel(peewee.Model)` and you'll be set.

**Comment by Waayway** [comment]
It now gives me a slightly different error
```
Traceback (most recent call last):
  File "/home/waayway/code/Dissonance/backend/app.py", line 6, in <module>
    from database import get_db, create_tables
  File "/home/waayway/code/Dissonance/backend/database/__init__.py", line 1, in <module>
    from . import database, models
  File "/home/waayway/code/Dissonance/backend/database/models.py", line 10, in <module>
    class User(baseModel):
  File "/home/waayway/code/Dissonance/backend/env/lib/python3.10/site-packages/peewee.py", line 6264, in __new__
    cls._meta.add_field(name, field)
  File "/home/waayway/code/Dissonance/backend/env/lib/python3.10/site-packages/peewee.py", line 6068, in add_field
    field.bind(self.model, field_name, set_attribute)
  File "/home/waayway/code/Dissonance/backend/env/lib/python3.10/site-packages/peewee.py", line 5464, in bind
    super(ManyToManyField, self).bind(model, name, set_attribute)
  File "/home/waayway/code/Dissonance/backend/env/lib/python3.10/site-packages/peewee.py", line 4592, in bind
    setattr(model, name, self.accessor_class(model, self, name))
  File "/home/waayway/code/Dissonance/backend/env/lib/python3.10/site-packages/peewee.py", line 5404, in __init__
    self.through_model = field.through_model
  File "/home/waayway/code/Dissonance/backend/env/lib/python3.10/site-packages/peewee.py", line 5485, in through_model
    self._through_model = self._create_through_model()
  File "/home/waayway/code/Dissonance/backend/env/lib/python3.10/site-packages/peewee.py", line 5494, in _create_through_model
    tables = [model._meta.table_name for model in (lhs, rhs)]
  File "/home/waayway/code/Dissonance/backend/env/lib/python3.10/site-packages/peewee.py", line 5494, in <listcomp>
    tables = [model._meta.table_name for model in (lhs, rhs)]
AttributeError: 'NoneType' object has no attribute '_meta'
```

**Comment by Waayway** [comment]
Found the issue, i had the manytomany fields model=None
