### ISSUE TITLE
run test for MySQL 8.0 failed 

### ISSUE THREAD

**Issue by siddontang** [coleifer/peewee#2574]
Hi, I tried to run the test for MySQL 8.0 as `python3 ./runtests.py -e mysql --mysql-user=root --mysql-port=3306`, but met some test failed, like:

```
ERROR: test_for_update_nested (tests.models.TestForUpdateIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tangliu/eng/show/peewee/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
  File "/opt/homebrew/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/opt/homebrew/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/opt/homebrew/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/homebrew/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/opt/homebrew/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/opt/homebrew/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/opt/homebrew/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/homebrew/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1093, "You can't specify target table 'users' for update in FROM clause")

......

Ran 891 tests in 32.490s

FAILED (failures=4, errors=3, skipped=105)
```

**Comment by coleifer** [comment]
That's alright, we test using MariaDB.
