### ISSUE TITLE
Cannot create BlobField with mysql-connector

### ISSUE THREAD

**Issue by Kamigaku** [coleifer/peewee#2729]
Hey everyone,

I'm developing a software under python 3.11 with peewee connecting to a MySQL database through the mysql-connector (https://dev.mysql.com/doc/connector-python/en/) but I can't manage to create a model with a BlobField.
Below you will find a reproducible code with the stack trace.

```
sqlConnection = MySQLConnectorDatabase("my_db",
                                       user="root",
                                       password="my_pwd",
                                       host="localhost",
                                       port=3306)

sqlConnection.connect()


class Building(Model):
    name = CharField(max_length=255)
    emoji = BlobField()

    class Meta:
        database = sqlConnection


if __name__ == '__main__':
    sqlConnection.create_tables([Building])
```

Generated stack trace when running:

```
Traceback (most recent call last):
  File ".\main.py", line 22, in <module>
    class Building(Model):
  File ".\Lib\site-packages\peewee.py", line 6411, in __new__
    cls._meta.add_field(name, field)
  File ".\Lib\site-packages\peewee.py", line 6194, in add_field
    field.bind(self.model, field_name, set_attribute)
  File ".\Lib\site-packages\peewee.py", line 4946, in bind
    self._db_hook(model._meta.database)
  File ".\Lib\site-packages\peewee.py", line 4938, in _db_hook
    self._constructor = database.get_binary_type()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\Lib\site-packages\peewee.py", line 4237, in get_binary_type
    return mysql.Binary
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Binary'
```

Is it possible to create those type of field?
On a side note, i'm not gonna switch to PyMysql because of the PEP-249 that doesn't allow me to retrieve OUT variables when doing a stored procedure.

**Comment by coleifer** [comment]
Yes this is an oversight on my part. You can temporarily override the `get_binary_type` method to return `mysql_connector.Binary`. I'll get a patch soon.

**Comment by coleifer** [comment]
Fixed in 79b6ebe29d2a4088977dc16fddd1b0d7aedc7a19
