### ISSUE TITLE
After a period of inactivity, peewee fails to perform database operations through the database connection

### ISSUE THREAD

**Issue by frelion** [coleifer/peewee#2736]
For the humble test script below
After one hour of inactivity, the program will block on the `if not TestModel.table_exists():` line
```python
import time
import random

from peewee import *

from conn.mysql import db
text = "abcds"

class TestModel(Model):
    hello = CharField(null=True, max_length=16)
    class Meta:
        table_name = "test_alive_db_conn"
        database = db

def test():
    print("check table exists")
    if not TestModel.table_exists():
        print("table not exists")
        TestModel.create_table()
    print("table already created")
    hello = text[random.randint(0, 4)].join(["1", "2", "3"])
    print("hello: ", hello)
    a = TestModel(hello=hello)
    print("insert hello")
    a.save()
    print("insert over")

test()
time.sleep(60*60)
test()
```

The following is conn.mysql
```python
import os
import json
import logging
from abc import ABC

from playhouse.shortcuts import ReconnectMixin
from playhouse.pool import PooledMySQLDatabase

class ReconnectMySQLDatabase(ReconnectMixin, PooledMySQLDatabase, ABC):
    pass

dir = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(dir, "config.json"), mode="rt", encoding="utf-8") as f:
    config = json.load(f)['MySQL']

try:
    db = ReconnectMySQLDatabase(**{
        **config,
        'autocommit': True
        })
except Exception as e:
    logging.error("db connection error: %s", e)
    exit(1)
```

I used many methods on the Internet to try to solve this problem, and even directly replaced the db conn(😂) of TestModel, but it didn’t work.

**Comment by coleifer** [comment]
Are you able to find out where it's blocking, for example if you interrupt your script what is the traceback that is printed?

My instinct is that I don't believe this is a Peewee bug. The `ReconnectMixin` also works by detecting an error raised by the mysql client library (for example "2006: MySQL server has gone away", "4031: Client interaction timeout"). It seems like in your case the mysql client is not raising an error at all, and is simply blocking? I'm not sure there's much we can do in that case.

You might try something like the following to see if you can get closer to the actual issue:

```python
import pymysql
conn = pymysql.connect(database='db name', ...)
# Execute a query right away.
curs = conn.cursor()
curs.execute('select table_name from information_schema.tables limit 1')
curs.fetchone()  # Read a single row.

# Sleep for one hour.
time.sleep(60 * 60)

# Attempt to execute another query.
curs = conn.cursor()
curs.execute('select table_name from information_schema.tables limit 1')
curs.fetchone()  # Read a single row.
```

I will reopen if it looks like there's anything for us to do.

In the meantime, I recommend against keeping a connection open for so long and use good practices of opening and closing connections when you're done with them. You will also want to specify a stale timeout on the pool.

```python
# If a connection is idle in the pool for >10 minutes, do not recycle it.
db = ReconnectMySQLDatabase(..., stale_timeout=600)
```

**Comment by frelion** [comment]
you right, maybe it is not a peewee problem.
```shell
^CTraceback (most recent call last):
  File "/home/sunzibin/project/osd/test.py", line 151, in <module>
    test()
  File "/home/sunzibin/project/osd/test.py", line 135, in test
    if not TestModel.table_exists():
  File "/home/sunzibin/.local/lib/python3.10/site-packages/peewee.py", line 6851, in table_exists
    return cls._schema.database.table_exists(M.table.__name__, M.schema)
  File "/home/sunzibin/.local/lib/python3.10/site-packages/peewee.py", line 3403, in table_exists
    return table_name in self.get_tables(schema=schema)
  File "/home/sunzibin/.local/lib/python3.10/site-packages/peewee.py", line 4176, in get_tables
    return [table for table, in self.execute_sql(query, ('VIEW',))]
  File "/home/sunzibin/.local/lib/python3.10/site-packages/playhouse/shortcuts.py", line 256, in execute_sql
    return super(ReconnectMixin, self).execute_sql(sql, params)
  File "/home/sunzibin/.local/lib/python3.10/site-packages/peewee.py", line 3236, in execute_sql
    cursor.execute(sql, params or ())
  File "/home/sunzibin/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/sunzibin/.local/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/sunzibin/.local/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/sunzibin/.local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/sunzibin/.local/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/sunzibin/.local/lib/python3.10/site-packages/pymysql/connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/sunzibin/.local/lib/python3.10/site-packages/pymysql/connections.py", line 732, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
```

**Comment by coleifer** [comment]
Looks like the issue occurs attempting to read the first byte. Surprised it doesn't report a problem attempting to write.

Maybe setting the pymysql `read_timeout` will help:

```
db = ReconnectMySQLDatabase(..., read_timeout=5)
```

You can try asking the pymysql people if they've seen this before, they may have other ideas.

**Comment by frelion** [comment]
Yes, I need to set the read_timeout parameter, otherwise the socket will put in blocking mode.
thank you very much
![image](https://github.com/coleifer/peewee/assets/71957494/9e7cf138-931f-4146-a50e-ab8117ec65bd)

**Comment by frelion** [comment]
I have a puzzle. I took your suggestion and specified stale_timeout=300 when initializing the database connection pool. I understand that when a database connection is idle for more than 5 minutes it will be discarded.🤔
So, after time.sleep(60 * 60), I actually re-establish a connection. But in fact the program is still blocked, it seems that it still reads the same socket file and waits for a timeout.(＠_＠;)
Thanks

**Comment by coleifer** [comment]
Did you try the code from here: https://github.com/coleifer/peewee/issues/2736#issuecomment-1569423261 ? I'm assuming it behaves the same.

I also just realized you have `autocommit` set to True. You might try disabling that, since Peewee comes with a rather strong warning against using it. Peewee queries run in autocommit already, unless you explicitly wrap them in a transaction/atomic block: http://docs.peewee-orm.com/en/latest/peewee/database.html?highlight=autocommit#autocommit-mode

I've made a couple small changes to your original script, you might give them a try and see if it helps:

```
# conn setup:
try:
    db = ReconnectMySQLDatabase(stale_timeout=300, read_timeout=5, **config)
except Exception as e:
    logging.error("db connection error: %s", e)
    exit(1)


# script:
import time
import random

from peewee import *

from conn.mysql import db
text = "abcds"

class TestModel(Model):
    hello = CharField(null=True, max_length=16)
    class Meta:
        table_name = "test_alive_db_conn"
        database = db

def test():
    with db:  # Ensures conn open and closed properly.
        print("check table exists")
        if not TestModel.table_exists():
            print("table not exists")
            TestModel.create_table()
        print("table already created")
        hello = text[random.randint(0, 4)].join(["1", "2", "3"])
        print("hello: ", hello)
        a = TestModel(hello=hello)
        print("insert hello")
        a.save()
        print("insert over")

test()
time.sleep(60*60)
test()
```
```
