### ISSUE TITLE
To have a field mapped to backref

### ISSUE THREAD

**Issue by igoncharov85** [coleifer/peewee#2748]
Hi @coleifer!
Thank you very much for this great ORM framework.

I just recently started to use it and love it a lot.

```
class User(Model):
    username = TextField()

class Tweet(Model):
    user = ForeignKeyField(User, backref='tweets')
    content = TextField()

user = User.create(username='huey')
Tweet.create(user=user, content='huey-1')
Tweet.create(user=user, content='huey-2')

query = user.tweets
```

Pycharm during its statical analysis highlights `tweets` with `Unresolved attribute reference 'tweets' for class 'User'` 

Can a collection field be created in the `User` class to avoid such an issue?
Thanks!

**Comment by coleifer** [comment]
This is, to me, not an issue with Peewee but a deficiency in the tool you're using. To modify one's code in order to workaround limitations in an IDE is, of course, your call... but you would:

```python
User.tweets = BackrefAccessor(Tweet.user)
```

I don't recommend this kind of thing one bit, though, because it's redundant and may make future changes to either Tweet or User fragile (e.g. if you wanted to change the backref name later, or something).

**Comment by igoncharov85** [comment]
Thanks for the answer.
This is the code I'm trying to use `BackrefAccessor `in

```
import peewee
from peewee import *

db = SqliteDatabase(':memory:')
print(peewee.__version__)

class DbModel(Model):
    class Meta:
        database = db

class UserData(DbModel):
    UserId = AutoField(primary_key=True)
    Login = CharField()

    Teacher = peewee.BackrefAccessor(Teacher.UserData)
    Student = peewee.BackrefAccessor(Student.UserData)

class Teacher(DbModel):
    SchoolName = CharField()
    UserData = ForeignKeyField(UserData, backref='Teacher', primary_key=True, object_id_name='TeacherId')

class Student(DbModel):
    University = CharField()
    UserData = ForeignKeyField(UserData, backref='Student', primary_key=True, object_id_name='StudentId')

db.create_tables([UserData, Teacher, Student])

with db.atomic():
    user_data = UserData.create(Login='user_login')
    teacher = Teacher.create(SchoolName='School1', UserData=user_data)
    student = Student.create(University='University1', UserData=user_data)

assert user_data.UserId == student.StudentId
assert user_data.Student == student
assert user_data.UserId == teacher.TeacherId
assert user_data.Teacher == teacher
```

How do I reference the class defined later in the code?

```
3.16.2
Traceback (most recent call last):
  File "C:\repos\GitHub\ukd-orm\peewee_orm\peewee_deferred.py", line 11, in <module>
    class UserData(DbModel):
  File "C:\repos\GitHub\ukd-orm\peewee_orm\peewee_deferred.py", line 15, in UserData
    Teacher = peewee.BackrefAccessor(Teacher.UserData)
                                     ^^^^^^^
NameError: name 'Teacher' is not defined
```

**Comment by coleifer** [comment]
>How do I reference the class defined later in the code?

Exactly. Just let peewee do it for you. If you aren't willing to do that, you need to wait until after the classes are defined and put the backref accessors on as I showed in my example code.
