### ISSUE TITLE
Specify a transaction isolation level when creating a connection?

### ISSUE THREAD

**Issue by ponponon** [coleifer/peewee#2790]
I referenced: https://github.com/coleifer/peewee/issues/1972 , but the problem persists!

Is there a convenient and elegant way to automatically set a specified transaction isolation level for each newly created database connection?

I also want a convenient way, for example when I try to set the isolation level parameter directly in atomic

```python
with db.atomic(isolation_level='SERIALIZABLE'):
    
    result = db.execute_sql("SELECT @@transaction_isolation;")
    current_isolation_level = result.fetchone()[0]
    print("Current transaction isolation level:", current_isolation_level)

```

Will report an error

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ponponon/Desktop/code/work/vobile-it/crawler_console/dev/peewee_test.py", line 9, in <module>
    with db.atomic(isolation_level='SERIALIZABLE'):
  File "/Users/ponponon/.local/share/virtualenvs/crawler_console-J8uqt1Xz/lib/python3.10/site-packages/peewee.py", line 4368, in __enter__
    return self._helper.__enter__()
  File "/Users/ponponon/.local/share/virtualenvs/crawler_console-J8uqt1Xz/lib/python3.10/site-packages/peewee.py", line 4403, in __enter__
    self._begin()
  File "/Users/ponponon/.local/share/virtualenvs/crawler_console-J8uqt1Xz/lib/python3.10/site-packages/peewee.py", line 4389, in _begin
    self.db.begin(*args, **kwargs)
TypeError: Database.begin() got an unexpected keyword argument 'isolation_level'
```

**Comment by coleifer** [comment]
This should now work:

```python
# Note: only applies to outermost `atomic()` block.
with db.atomic(isolation_level='SERIALIZABLE'):
    ....

# Or:
with db.transaction(isolation_level='SERIALIZABLE'):
    ....
```

**Comment by coleifer** [comment]
New doc: http://docs.peewee-orm.com/en/latest/peewee/api.html#PostgresqlDatabase.atomic

**Comment by ponponon** [comment]
> ```python
> transaction
> ```

Neither db.atomic nor db.transaction works

```python
from collections import namedtuple
from peewee import *
import settings
from playhouse.shortcuts import ReconnectMixin


host = settings.MYSQL_CONFIG.host
port = settings.MYSQL_CONFIG.port
username = settings.MYSQL_CONFIG.username
password = settings.MYSQL_CONFIG.password
database_name = settings.MYSQL_CONFIG.database_name


class ReconnectMySQLDatabase(ReconnectMixin, MySQLDatabase):
    pass


db = MySQLDatabase(
    database=database_name,
    host=host,
    port=port,
    user=username,
    password=password,
    charset='utf8mb4'
)

with db.atomic(isolation_level='SERIALIZABLE'):
    pass
```

The error is reported as follows

```shell
Traceback (most recent call last):
  File "/Users/ponponon/Desktop/code/me/peewee_example/main.py", line 27, in <module>
    with db.atomic(isolation_level='SERIALIZABLE'):
  File "/Users/ponponon/.local/share/virtualenvs/peewee_example-GOkHfhm6/lib/python3.11/site-packages/peewee.py", line 4368, in __enter__
    return self._helper.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ponponon/.local/share/virtualenvs/peewee_example-GOkHfhm6/lib/python3.11/site-packages/peewee.py", line 4403, in __enter__
    self._begin()
  File "/Users/ponponon/.local/share/virtualenvs/peewee_example-GOkHfhm6/lib/python3.11/site-packages/peewee.py", line 4389, in _begin
    self.db.begin(*args, **kwargs)
TypeError: Database.begin() got an unexpected keyword argument 'isolation_level'
```

换成 db.transaction 也会报错

```python
with db.transaction(isolation_level='SERIALIZABLE'):
    pass
```

Changing to db.transaction will also report an error

```shell
Traceback (most recent call last):
  File "/Users/ponponon/Desktop/code/me/peewee_example/main.py", line 27, in <module>
    with db.transaction(isolation_level='SERIALIZABLE'):
  File "/Users/ponponon/.local/share/virtualenvs/peewee_example-GOkHfhm6/lib/python3.11/site-packages/peewee.py", line 4403, in __enter__
    self._begin()
  File "/Users/ponponon/.local/share/virtualenvs/peewee_example-GOkHfhm6/lib/python3.11/site-packages/peewee.py", line 4389, in _begin
    self.db.begin(*args, **kwargs)
TypeError: Database.begin() got an unexpected keyword argument 'isolation_level'
```

**Comment by ponponon** [comment]
```shell
╰─➤  pip show peewee                                                                                                                                                                                                                                               1 ↵
Name: peewee
Version: 3.16.3
Summary: a little orm
Home-page: https://github.com/coleifer/peewee/
Author: Charles Leifer
Author-email: coleifer@gmail.com
License: MIT License
Location: /Users/ponponon/.local/share/virtualenvs/peewee_example-GOkHfhm6/lib/python3.11/site-packages
Requires: 
Required-by: 
```

**Comment by coleifer** [comment]
Yeah…this was only added for Postgres.

**Comment by coleifer** [comment]
So, oddly, this does *not* look like it will work with MySQL/MariaDB. I'm not sure why, to be honest -- check out this code (using both pymysql and mariadb-connector):

```python
import mariadb
import pymysql

for driver in (mariadb, pymysql):
    for autocommit in (True, False):
        conn = driver.connect(database='peewee_test', autocommit=autocommit)
        with conn.cursor() as curs:
            curs.execute('set transaction isolation level serializable')
            curs.execute('begin')
            curs.execute('select @@tx_isolation')
            print(curs.fetchone()[0])
            curs.execute('rollback')

# Output:
# REPEATABLE-READ
# REPEATABLE-READ
# REPEATABLE-READ
# REPEATABLE-READ
```

According to the docs, the `SET TRANSACTION ISOLATION LEVEL x` should apply to the **next** (not-yet-started) transaction within the current session -- I'm not sure, though, why it is not applying when we immediately begin a new transaction after setting the isolation level.

If we modify the query to `SET SESSION TRANSACTION ISOLATION LEVEL x` then it *does* work, but the change persists for the duration of the session, which doesn't really match the API we're targeting.

Even using the MariaDB shell I observe the same thing:

```
MariaDB [peewee_test]> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;                     
Query OK, 0 rows affected (0.000 sec)

MariaDB [peewee_test]> BEGIN;
Query OK, 0 rows affected (0.000 sec)

MariaDB [peewee_test]> SELECT @@tx_isolation;                                            
+-----------------+
| @@tx_isolation  |
+-----------------+
| REPEATABLE-READ |
+-----------------+
1 row in set (0.000 sec)
```

**Comment by coleifer** [comment]
Hmm... Maybe it's just that the `@@tx_isolation` is reporting the incorrect value, because the code is actually *behaving* like the isolation level was changed?

**Comment by coleifer** [comment]
Alright the tests show that it *is* working properly, and MariaDB just reports the wrong/incorrect value.

**Comment by ponponon** [comment]
> Alright the tests show that it _is_ working properly, and MariaDB just reports the wrong/incorrect value.
> 
> This is now added for MySQL/MariaDB.

Great, looking forward to releasing a new package to pypi

**Comment by coleifer** [comment]
3.17.0 release should be up now.
