### ISSUE TITLE
The coroutine is canceled

### ISSUE THREAD

**Issue by fallinloveq** [coleifer/peewee#2846]
Traceback (most recent call last):
  File "/external/src/__init__.py", line 62, in async_wrapper
    return await original_attr(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 272, in execute
    return (await execute(query))
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 432, in execute
    return (await coroutine(query))
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 580, in select
    return await _execute_with_returning(query)
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 564, in _execute_with_returning
    cursor = await _execute_query_async(query)
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 1480, in _execute_query_async
    return (await _run_sql(database, *query.sql()))
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 1460, in _run_sql
    cursor = await database.cursor_async()
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 882, in cursor_async
    await self.connect_async(loop=self._loop)
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 853, in connect_async
    await self._async_wait
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sanic/http/http1.py", line 127, in http1
    await self.protocol.request_handler(self.request)
  File "handle_request", line 97, in handle_request
  File "/external/src/monitor.py", line 58, in get_login_handler_monitor
    result = await request.app.ctx.db_manager.Base_manager.execute(query_ans_sql)
  File "/external/src/__init__.py", line 65, in async_wrapper
    await self.close()
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 307, in close
    await self.database.close_async()
  File "/usr/local/lib/python3.10/site-packages/peewee_async.py", line 899, in close_async
    await self._async_wait
asyncio.exceptions.CancelledError

-------------------------------------------------------------------------------------------
The PooledMySQLDatabase link is managed using peewee_async's Manager. 
An exception occurred when the coroutine was canceled while executing execute. We can't figure out why

**Comment by coleifer** [comment]
Try talking to the maintainer of the async peewee package. That’s not me.
