### ISSUE TITLE
启动项目后缺少public文件夹导致错误

### ISSUE THREAD

**Issue by YOHN89** [coleifer/peewee#2847]
`domain-admin  | 2024-02-28 12:14:48 [ERROR] handler.py/error_handler:
domain-admin  | Traceback (most recent call last):
domain-admin  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
domain-admin  |     rv = self.dispatch_request()
domain-admin  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
domain-admin  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
domain-admin  |   File "/app/domain_admin/main.py", line 53, in index
domain-admin  |     return send_file('public/index.html')
domain-admin  |   File "/usr/local/lib/python3.7/site-packages/flask/helpers.py", line 547, in send_file
domain-admin  |     max_age=max_age,
domain-admin  |   File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 440, in send_file
domain-admin  |     stat = os.stat(path)
domain-admin  | FileNotFoundError: [Errno 2] No such file or directory: '/app/domain_admin/public/index.html'
`

** No such file or directory: '/app/domain_admin/public/index.html'**

是在docker下部署的，检查了一下容器里的文件夹，确实没有public文件夹

**Comment by YOHN89** [comment]
是在docker下部署的
