### ISSUE TITLE
CompositeKey with the single column leads to unexpected error.

### ISSUE THREAD

**Issue by recipe** [coleifer/peewee#2857]
By some reason I need to have two model classes with similar columns but different primary keys. If I use the `primary_key = peewee.CompositeKey("column")` in the first one the `model_class.get_by_id()` method starts failing with the `TypeError: 'int' object is not iterable` error. Check the full example below:

```shell
$ python -V               
Python 3.10.10

$ pip freeze | grep peewee
peewee==3.17.0
```

```python
import peewee

db = peewee.MySQLDatabase(
    "db", user="app", password="b", host="localhost", port=13312
)


class BaseModel(peewee.Model):
    class Meta:
        database = db
        only_save_dirty = True


class BaseItem(BaseModel):
    third = peewee.IntegerField()
    column1 = peewee.IntegerField()
    column2 = peewee.CharField()


class Item(BaseItem):
    class Meta:
        table_name = "item"
        primary_key = peewee.CompositeKey("third")


class ItemHistory(BaseItem):
    year_week = peewee.IntegerField()

    class Meta:
        table_name = "item_history"
        primary_key = peewee.CompositeKey("third", "year_week")


db.create_tables([Item, ItemHistory])

# Tables created as expected:

# SHOW CREATE TABLE item;

# CREATE TABLE `item` (
#     `third` int NOT NULL,
# `column1` int NOT NULL,
# `column2` varchar(255) NOT NULL,
# PRIMARY KEY (`third`)
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


# SHOW CREATE TABLE item_history;

# CREATE TABLE `item_history` (
#     `third` int NOT NULL,
# `column1` int NOT NULL,
# `column2` varchar(255) NOT NULL,
# `year_week` int NOT NULL,
# PRIMARY KEY (`third`,`year_week`)
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


Item.insert_many(
    {"third": 1, "column1": 21, "column2": "test"}
).on_conflict_ignore().execute()

# SELECT FROM items;
# +-----+-------+-------+
# |third|column1|column2|
# +-----+-------+-------+
# |1    |21     |test   |
# +-----+-------+-------+

# This works well.
item = Item.select().where(Item.third == 1).get()

# This fails with the error:
Item.get_by_id(1)

# Traceback (most recent call last):
# File "/private/test/test.py", line 74, in <module>
# Item.get_by_id(1)
# File "/Users/vitaliy/.pyenv/versions/reg/lib/python3.10/site-packages/peewee.py", line 6723, in get_by_id
# return cls.get(cls._meta.primary_key == pk)
# File "/Users/vitaliy/.pyenv/versions/reg/lib/python3.10/site-packages/peewee.py", line 5761, in __eq__
# for field, value in zip(self.field_names, other)]
# TypeError: 'int' object is not iterable

```

**Comment by recipe** [comment]
I haven't found a better way than to fix the class declaration like this:

```python
class Item(BaseItem):
    class Meta:
        table_name = "item"

Item._meta.primary_key = Item.third
```

I think, for the best, the error should have been there `primary_key = peewee.CompositeKey("third")`. Because a composite key is a combination of two or more than two columns.

**Comment by coleifer** [comment]
`CompositeKey` is only intended to be used when you have a primary key that uses multiple columns. I'm not sure what you're trying to do here.

**Comment by recipe** [comment]
@coleifer Would you mind rising an exception when someone is trying to use it in this way `peewee.CompositeKey("third")`?
