### ISSUE TITLE
Installation broken: No module named 'peewee'  (v3.17.4) 

### ISSUE THREAD

**Issue by romeroyonatan** [coleifer/peewee#2891]
Hello peewee contributors

I found the installation of the latest version (3.17.4) is failing with python 3.12.3

```sh
$ python --version                  
Python 3.12.3
$ pip install peewee==3.17.4
Collecting peewee==3.17.4
  Using cached peewee-3.17.4.tar.gz (3.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/tmp/a/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/a/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/a/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6o22jxes/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6o22jxes/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-6o22jxes/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 196, in <module>
        File "<string>", line 150, in _do_setup
      ModuleNotFoundError: No module named 'peewee'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Thanks for your time

Have a nice day

**Comment by coleifer** [comment]
Thanks for the quick report, I suppose I really need to check pip install against every version. We can all be grateful for @pypa's stewardship and truly creating makework and problems where previously everything worked great.

3.17.5 should be up now and working.

**Comment by coleifer** [comment]
You gotta be quick when packaging is in the mix!

**Comment by romeroyonatan** [comment]
Thank you very much for the quick fix. Amazing
