### ISSUE TITLE
peewee.OperationalError: Connection already opened.

### ISSUE THREAD

**Issue by NorthWind555** [coleifer/peewee#2936]
When I use gevent.spawn to run two tasks that interact with MySQL simultaneously, I get an error message saying "Connection already opened."

If you replace gevent with threading or multiprocessing, the program will run normally.

`python3.8
peewee==3.17.6`

```python
import datetime
import time

from peewee import *

import gevent.monkey
from playhouse.pool import PooledMySQLDatabase

gevent.monkey.patch_all(ssl=False)

database = PooledMySQLDatabase(
    "xxx",
    max_connections=50,
    stale_timeout=300,  # 5 minutes
    timeout=30,  # seconds to block when pool is full, 0 for indefinitely
    user="root",
    password="xxx",
    host="xxx",
    port=3306,
)


class BaseModel(Model):
    class Meta:
        database = database


class TLock(BaseModel):
    name = CharField(primary_key=True)
    locked_at = DateTimeField()
    lock_until = DateTimeField()
    locked_by = CharField()

    class Meta:
        table_name = 't_lock'


class TLockDao(object):
    @classmethod
    def acquire_lock(cls, name, locked_by, lock_time=60) -> bool:
        now = database.execute_sql('SELECT NOW()').fetchone()[0]
        lock_until = now + datetime.timedelta(seconds=lock_time)
        try:
            TLock.create(
                name=name,
                locked_at=now,
                lock_until=lock_until,
                locked_by=locked_by
            )
            return True
        except IntegrityError:
            try:
                existing_lock = (
                    TLock
                    .select(TLock.name, TLock.lock_until)
                    .where(TLock.name == name)
                    .get()
                )
            except DoesNotExist:
                return False

            if existing_lock.lock_until < now:
                query = TLock.update(
                    locked_at=now,
                    lock_until=lock_until,
                    locked_by=locked_by
                ).where(
                    (TLock.name == existing_lock.name) &
                    (TLock.lock_until == existing_lock.lock_until)
                )
                updated_rows = query.execute()
                return updated_rows > 0
            else:
                return False

    @classmethod
    def release_lock(cls, name) -> bool:
        query = TLock.delete().where(TLock.name == name)
        affected_rows = query.execute()
        if affected_rows > 0:
            return True
        else:
            return False


def print_num():
    print(1)
    print(hex(id(TLockDao)))
    lock = TLockDao.acquire_lock('print_num', 'xxx', lock_time=60)
    print(hex(id(TLockDao)))
    if lock:
        try:
            print('====== Start to run print_num process ======')
            for i in range(20):
                print('print_num: %s' % i)
                time.sleep(0.1)
            print('====== End of print_num process ======')
        except Exception as e:
            print(e)
        finally:
            TLockDao.release_lock('print_num')


def get_peak_data():
    print("get_peak_data", hex(id(TLockDao)))
    lock = TLockDao.acquire_lock('get_peak_data', 'xxx', lock_time=60)
    print("get_peak_data", hex(id(TLockDao)))
    if lock:
        try:
            print('====== Start to run get_peak_data process ======')
            print(1111)
            print('====== End of get_peak_data process ======')
        except Exception as e:
            print(e)
        finally:
            TLockDao.release_lock('get_peak_data')


if __name__ == '__main__':
    greenlet1 = gevent.spawn(print_num)
    greenlet2 = gevent.spawn(get_peak_data)

    gevent.joinall([greenlet1, greenlet2])

``` 

here is exception
```
Traceback (most recent call last):
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 3321, in execute_sql
    cursor = self.cursor()
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 3311, in cursor
    self.connect()
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/playhouse/pool.py", line 133, in connect
    ret = super(PooledDatabase, self).connect(reuse_if_open)
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 3259, in connect
    raise OperationalError('Connection already opened.')
peewee.OperationalError: Connection already opened.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/zehuixie/cvm/cvm-apiv3-framework/bug_demo.py", line 113, in get_peak_data
    lock = TLockDao.acquire_lock('get_peak_data', 'xxx', lock_time=60)
  File "/Users/zehuixie/cvm/cvm-apiv3-framework/bug_demo.py", line 45, in acquire_lock
    now = database.execute_sql('SELECT NOW()').fetchone()[0]
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 3322, in execute_sql
    cursor.execute(sql, params or ())
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 3088, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 196, in reraise
    raise value.with_traceback(tb)
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 3321, in execute_sql
    cursor = self.cursor()
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 3311, in cursor
    self.connect()
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/playhouse/pool.py", line 133, in connect
    ret = super(PooledDatabase, self).connect(reuse_if_open)
  File "/Users/zehuixie/miniconda3/envs/py38/lib/python3.8/site-packages/peewee.py", line 3259, in connect
    raise OperationalError('Connection already opened.')
peewee.OperationalError: Connection already opened.
2024-09-29T07:48:01Z <Greenlet at 0x101e35bf0: get_peak_data> failed with OperationalError
```

**Comment by NorthWind555** [comment]
My mistake
`import gevent.monkey; gevent.monkey.patch_all(ssl=False)`
should be at the beginning.
