### ISSUE TITLE
peewee tries to use psycopg2 even though only psycopg(3) is installed

### ISSUE THREAD

**Issue by jwulfheide-gb** [coleifer/peewee#2938]
Hi, I am using peewee through huey with the `SqlHuey` component.

Recently, I switched from using `psycopg2` to `psycopg`. Now I get the following error because `psycopg2` is not installed anymore, but peewee tries to use it.

```
Traceback (most recent call last):
  File "/usr/local/bin/manage.py", line 30, in <module>
    main()
  File "/usr/local/bin/manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/app/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/app/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/app/.venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/app/.venv/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/.venv/lib/python3.12/site-packages/huey/contrib/djhuey/__init__.py", line 101, in <module>
    HUEY = backend_cls(name, **huey_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/huey/api.py", line 119, in __init__
    self.storage = self.create_storage()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/huey/api.py", line 144, in create_storage
    return self.get_storage(**self.storage_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/huey/api.py", line 156, in get_storage
    return Storage(self.name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/huey/contrib/sql_huey.py", line 33, in __init__
    self.KV, self.Schedule, self.Task = self.create_models()
                                        ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/huey/contrib/sql_huey.py", line 41, in create_models
    class KV(Base):
  File "/app/.venv/lib/python3.12/site-packages/peewee.py", line 6575, in __new__
    cls._meta.add_field(name, field)
  File "/app/.venv/lib/python3.12/site-packages/peewee.py", line 6358, in add_field
    field.bind(self.model, field_name, set_attribute)
  File "/app/.venv/lib/python3.12/site-packages/peewee.py", line 5046, in bind
    self._db_hook(model._meta.database)
  File "/app/.venv/lib/python3.12/site-packages/peewee.py", line 5038, in _db_hook
    self._constructor = database.get_binary_type()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/peewee.py", line 4139, in get_binary_type
    return psycopg2.Binary
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Binary'
```

I understand that `psycopg` is supposed to be supported, right? Is this a configuration issue?

**Comment by coleifer** [comment]
Can you share your settings for Huey? Specifically what are you passing for the `database` parameter?

**Comment by coleifer** [comment]
I've added a commit which adds `psycopg3` as a recognized scheme for database URL configuration, so going forwards you should be able to:

```
huey = SqlHuey(database='psycopg3:///my_database')
```

In the meantime, though, you will need to directly instantiate and pass it to the storage engine:

```
from playhouse.psycopg3_ext import Psycopg3Database
db = Psycopg3Database('my_database')
huey = SqlHuey(database=db)
```

**Comment by jwulfheide-gb** [comment]
thanks, explicitly setting the scheme to `psycopg3` works just fine.
