### ISSUE TITLE
Inserting record into link table throws OperationalError

### ISSUE THREAD

**Issue by rotsj** [coleifer/peewee#522]
Am trying to insert a record into a link table but getting an OperationalError thrown. I believe my model definitions are correct, but any feedback is welcome.

Output:

```
Traceback (most recent call last):
  File "permDb.py", line 129, in <module>
    main()
  File "permDb.py", line 22, in main
    setup()
  File "permDb.py", line 85, in setup
    convertConfig()
  File "permDb.py", line 118, in convertConfig
    project_team.save()
  File "/home/xrogder/scripts/peewee.py", line 3887, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/home/xrogder/scripts/peewee.py", line 2614, in execute
    return self.database.rows_affected(self._execute())
  File "/home/xrogder/scripts/peewee.py", line 2243, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/xrogder/scripts/peewee.py", line 2877, in execute_sql
    self.commit()
  File "/home/xrogder/scripts/peewee.py", line 2732, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/home/xrogder/scripts/peewee.py", line 2869, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: near "WHERE": syntax error
```

My models are:
```python
database = peewee.SqliteDatabase("wee.db")

class Project(peewee.Model):
    name = peewee.CharField(unique=True)
    class Meta:
        database = database

class Team(peewee.Model):
    name = peewee.CharField(unique=True)
    class Meta:
        database = database

class Project_Team(peewee.Model):
    project = peewee.ForeignKeyField(Project)
    team = peewee.ForeignKeyField(Team)
    class Meta:
        database = database
        primary_key = peewee.CompositeKey('project', 'team')
```

The code that's executing the insert:
```python
for project in Project.select():
    new_team = Team()
    new_team.name = team
    try:
        new_team.save()
        project_team = Project_Team()
        #print "project id ", project.id
        #print "team id ", new_team.id
        project_team.project = project.id
        project_team.team = new_team.id
        project_team.save()
    except peewee.IntegrityError:
        # Team already exists
        pass
```

The commented out print statements have shown me that both values exist. In this case, we've just created the first record in the Team table and are now trying to link it to the first project. (1,1)

**Comment by coleifer** [comment]
The problem is the call to `project_team.save()`. Because this model has a non-auto-incrementing primary key, if you are `INSERT`-ing a row you need to call `save(force_insert=True)`.

http://docs.peewee-orm.com/en/latest/peewee/models.html#id3

**Comment by rotsj** [comment]
Works like a charm, but I guess you'd expect that. Thanks!
