### ISSUE TITLE
Unable to create json or jsonb columns in Postgres 9.4

### ISSUE THREAD

**Issue by wishabhilash** [coleifer/peewee#567]
Am trying to create a table with a jsonb column but its keeps on giving me error.

    from peewee import *
    from playhouse.postgres_ext import BinaryJSONField

    db = PostgresqlDatabase(database="test")

    class JSONTest3(Model):
        username = BinaryJSONField()

        class Meta:
            database = db

    if __name__ == '__main__':
        db.connect()
        db.create_tables([JSONTest3])

My lib versions are:
    Postgres  == 9.4
    psycopg2 == 2.6

Error is:
    Traceback (most recent call last):
      File "peeweepostgres.py", line 16, in <module>
        db.create_tables([JSONTest3])
      File "/home/wish/virtualenv/local/lib/python2.7/site-packages/peewee.py", line 3042, in create_tables
        create_model_tables(models, fail_silently=safe)
      File "/home/wish/virtualenv/local/lib/python2.7/site-packages/peewee.py", line 4163, in create_model_tables
        m.create_table(**create_table_kwargs)
      File "/home/wish/virtualenv/local/lib/python2.7/site-packages/peewee.py", line 3911, in create_table
        db.create_table(cls)
      File "/home/wish/virtualenv/local/lib/python2.7/site-packages/peewee.py", line 3039, in create_table
        return self.execute_sql(*qc.create_table(model_class, safe))
      File "/home/wish/virtualenv/local/lib/python2.7/site-packages/peewee.py", line 1718, in inner
        return self.parse_node(fn(*args, **kwargs))
      File "/home/wish/virtualenv/local/lib/python2.7/site-packages/peewee.py", line 1746, in _create_table
        columns.append(self.field_definition(field))
      File "/home/wish/virtualenv/local/lib/python2.7/site-packages/peewee.py", line 1696, in field_definition
        column_type = self.get_column_type(field.get_db_field())
      File "/home/wish/virtualenv/local/lib/python2.7/site-packages/peewee.py", line 1325, in get_column_type
        return self._field_map[f]
     KeyError: 'json'

What can be the error am doing here???

**Comment by coleifer** [comment]
You need to use playhouse.postgres_ext.PostgresqlExtDatabase.

**Comment by wishabhilash** [comment]
Ohh thanks... :+1:
