### ISSUE TITLE
FTSModels for sqlite pass `options` that are not expected.

### ISSUE THREAD

**Issue by mklauber** [coleifer/peewee#603]
I'm having an issue with using the sqlite_ext FTS extension.  I'm trying to follow the example from the documentation (reproduced below), but I'm getting the following stack trace.  (reproduced *further* below).  Am I missing something, or is this part of the general experimental nature of the sqlite_ext?

```python
class Metadata(Model):
    document  = ForeignKeyField(Document)
    field = CharField(index=True)
    content = TextField()

    class Meta:
        database = db

class MetadataIndex(FTSModel):
    value = TextField()

    class Meta:
        database = db


Metadata.create_table()
MetadataIndex.create_table(value=Metadata.content)
```

```python
Traceback (most recent call last):
  File "models.py", line 43, in <module>
    MetadataIndex.create_table()
  File "/home/mklauber/.virtualenvs/metalogos/local/lib/python2.7/site-packages/playhouse/sqlite_ext.py", line 107, in create_table
    cls._meta.database.create_table(cls, options=options)
TypeError: create_table() got an unexpected keyword argument 'options'
```

**Comment by mklauber** [comment]
Doh, Found it in the closed issues.  Sorry.
