### ISSUE TITLE
updating peewee on windows

### ISSUE THREAD

**Issue by hgabe** [coleifer/peewee#653]
running build_ext
building 'playhouse.speedups' extension
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    scripts = ['pwiz.py'],
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 67,
n run
    self.do_egg_install()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 109,
in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 16
, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Python34\lib\site-packages\setuptools\command\bdist_egg.py", line 14
, in call_command
    self.run_command(cmdname)
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install_lib.py", line
0, in run
    self.build()
  File "C:\Python34\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 50
 in run
    _build_ext.run(self)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_ext
nsions
    self.build_extension(ext)
  File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 18
, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_ext
nsion
    depends=ext.depends)
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile
    self.initialize()
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python34\lib\site-packages\setuptools\msvc9_support.py", line 52, in
query_vcvarsall
    return unpatched['query_vcvarsall'](version, *args, **kwargs)
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsa
l
    raise ValueError(str(list(result.keys())))
ValueError: ['path']

I have VS2010, 2012 and VS2013 community install
I tried to upgrade it with both git and pip using python 3.4.3

**Comment by hgabe** [comment]
please close this issue found the solution in here

https://msdn.microsoft.com/en-us/library/x4d2c09s.aspx

then pip install

**Comment by coleifer** [comment]
Thanks @hgabe !
