### ISSUE TITLE
Property getters/setters don't work with `get_or_create`

### ISSUE THREAD

**Issue by plaidfluff** [coleifer/peewee#661]
This is on version 2.6.3, as installed via OSX's `easy_install` function.

I have a project in which I'd like to automatically derive a human-readable sorting key from a title (or in this case, a band name). I have this code for it (simplified):

    def to_key(name):
        return re.sub(r'^(a|the) (.*)$', r'\2, \1', name.lower())
    
    class Band(BaseModel):
        @property
        def name(self):
            return self.display_name

        @name.setter
        def name(self, value):
            self.display_name = value
            self.sort_key = to_key(value)

        sort_key = CharField(unique=True)
        display_name = CharField(unique=True)

This works fine with the model constructor:

    >>> band = Band(name='The stupidest band name ever')
    >>> band.sort_key
    'stupidest band name ever, the'
    >>> band.display_name
    'The stupidest band name ever'
    >>> band.save()
    1

but if I try to use it through `get_or_create` I get an error:

    >>> band,created = Band.get_or_create(name="The Terrible Trio")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "build/bdist.macosx-10.10-intel/egg/peewee.py", line 4145, in get_or_create
      File "build/bdist.macosx-10.10-intel/egg/peewee.py", line 2740, in get
      File "build/bdist.macosx-10.10-intel/egg/peewee.py", line 2787, in execute
      File "build/bdist.macosx-10.10-intel/egg/peewee.py", line 2470, in _execute
      File "build/bdist.macosx-10.10-intel/egg/peewee.py", line 3199, in execute_sql
      File "build/bdist.macosx-10.10-intel/egg/peewee.py", line 3048, in __exit__
      File "build/bdist.macosx-10.10-intel/egg/peewee.py", line 3191, in execute_sql
    peewee.InterfaceError: Error binding parameter 0 - probably unsupported type.

although if I explicitly set the individual properties it's fine:

    >>> band,created = Band.get_or_create(display_name="Harry",sort_key="Larry")
    >>> created
    True
    >>> band.name
    'Harry'
    >>> band.display_name
    'Harry'
    >>> band.sort_key
    'Larry'

Supporting this isn't a particularly big deal for this project, but it'd be a nice to have.

The obvious question would be how to support ambiguous things like:

    Band.get_or_create(name="The Sugar Shock")
    Band.get_or_create(name="Sugar Shock, The")

In this case I'd expect the first one to create a new entry with `display_name='The Sugar Shock'` and the second one to throw an exception because it'd try to create a new entry that violates the uniqueness constraint on `sort_key`, but I'm not sure if that's generally the correct thing to expect (or if this even makes a lick of sense in general).

**Comment by plaidfluff** [comment]
Closing, because I realized that the underlying problem is with `get` and that trying to do a `get` on a derived key like this makes no dang sense.
