### ISSUE TITLE
Foreign key collision regarding related_name

### ISSUE THREAD

**Issue by dzeban** [coleifer/peewee#740]
I have 2 tables
```sql
CREATE TABLE "Feed"
(
  id serial NOT NULL,
  url text,
  CONSTRAINT "Feed_pkey" PRIMARY KEY (id)
)
CREATE TABLE "Entry"
(
  id serial NOT NULL,
  link text,
  feed_id integer,
  CONSTRAINT "Entry_pkey" PRIMARY KEY (id),
  CONSTRAINT "Entry_feed_id_fkey" FOREIGN KEY (feed_id)
      REFERENCES "Feed" (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
```

Next I'm generating models with pwiz:

```python
from peewee import *

database = PostgresqlDatabase('test', **{'host': 'localhost', 'user': 'ribbo'})

class UnknownField(object):
    pass

class BaseModel(Model):
    class Meta:
        database = database

class Feed(BaseModel):
    url = TextField(null=True)

    class Meta:
        db_table = 'Feed'

class Entry(BaseModel):
    feed = ForeignKeyField(db_column='feed_id', null=True, rel_model=Feed, to_field='id')
    link = TextField(null=True)

    class Meta:
        db_table = 'Entry'
```

But when I'm subclassing on Entry I get the error:

```python
$ cat Entry.py 
from models import database
from models import Entry as EntryModel

class Entry(EntryModel):
    myattr = 'somestring'

    def some():
        print('Hi')

e = Entry()
```
```
$ python3 Entry.py 
Traceback (most recent call last):
  File "Entry.py", line 4, in <module>
    class Entry(EntryModel):
  File "/usr/lib/python3.4/site-packages/peewee.py", line 4224, in __new__
    field.add_to_class(cls, name)
  File "/usr/lib/python3.4/site-packages/peewee.py", line 1250, in add_to_class
    self.model_class._meta.name, self.name, self.related_name))
AttributeError: Foreign key: entry.feed related name "entry_set" collision with foreign key using same related_name.
```

The fun part is that if I change `class Entry(EntryModel)` class name to `class Entry2(EntryModel)` problem disappears.

**Comment by coleifer** [comment]
I wouldn't consider this an error per se, just a quirk of the way peewee does backref validation. If you want to suppress the error, just declare your model with `validate_backrefs = False`:

```python
class Entry(BaseModel):
    class Meta:
        validate_backrefs = False
```
