### ISSUE TITLE
OperationalError when deferring foreign keys

### ISSUE THREAD

**Issue by notdaniel** [coleifer/peewee#748]
I've been trying to use the Proxy() trick, followed by its initialization, then table creation, and finally foreign key creation, exactly as shown in the [Circular foreign key dependencies](https://peewee.readthedocs.org/en/latest/peewee/models.html?highlight=defer#circular-foreign-key-dependencies) documentation. However, I always receive the following error:
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/dkh/devel/peeweetest/venv/lib/python2.7/site-packages/peewee.py", line 3436, in create_foreign_key
    model_class, field, constraint))
  File "/home/dkh/devel/peeweetest/venv/lib/python2.7/site-packages/peewee.py", line 3339, in execute_sql
    self.commit()
  File "/home/dkh/devel/peeweetest/venv/lib/python2.7/site-packages/peewee.py", line 3185, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/dkh/devel/peeweetest/venv/lib/python2.7/site-packages/peewee.py", line 3331, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: near "CONSTRAINT": syntax error
```
Wondering if it was with my models or something else on my end, I have tried using the exact models and code on the documentation with the same result. Any thoughts?

**Comment by coleifer** [comment]
What database are you using?

**Comment by notdaniel** [comment]
Ha! I was using SQLite (which I usually use when starting something out) but after your response, I just tried it with Postgres and it worked fine. Is this a SQLite limitation, then? Either way, this is helpful since I was going to move this to Postgres eventually anyway.

**Comment by coleifer** [comment]
SQLite does not support adding constraints. So basically you can follow the documentation example and simply skip the call to add the constraint. I've added a test and updated the docs to make this clear.
