### ISSUE TITLE
peewee 2.8.1 blob error

### ISSUE THREAD

**Issue by rfyiamcool** [coleifer/peewee#984]
in peewee 2.8.1 ,  use BlobField() raise error .

my peewee model example:
```
class ArticleContent(Model):
    article_id = IntegerField()
    content = BlobField()

    class Meta:
        database = db
        db_table= 'mirro_article_content'
```
error:
```
[operation@wx-buzz-zhihu2 extractor_mirro]$ python core/mm.py
Traceback (most recent call last):
  File "core/mm.py", line 30, in <module>
    class ArticleContent(Model):
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 4479, in __new__
    field.add_to_class(cls, name)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 1081, in add_to_class
    self._constructor = model_class._meta.database.get_binary_type()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3985, in get_binary_type
    return mysql.Binary
AttributeError: 'NoneType' object has no attribute 'Binary'
```

I use peewee 2.8.0 version, not raise error.   Please fix it .

**Comment by coleifer** [comment]
So this error indicates that the `mysql` Python driver is not installed or is not import-able. Here is the code peewee executes at the top of the module:

```python
try:
    import MySQLdb as mysql  # prefer the C module.
except ImportError:
    try:
        import pymysql as mysql
    except ImportError:
        mysql = None
```

You've triggered the "mysql=None" bit, meaning peewee could not import either driver.
